### ISSUE TITLE
1.4.5 crashes for invalid RegEx

### ISSUE THREAD

**Issue by mswiege** [ioBroker/ioBroker.vis#422]
**Describe the bug**  
I have an HTML module in my vis that contains some JS containing some oid bindings. Since version 1.4.5 in some cases, this module crashes the web instance and I get into a crash-loop (vis reloading -> crash -> vis reloading...). In 1.4.4 everything worked, which means one change in 1.4.5 was made to the replacement of oid's in the vis that does some wrong regEx replacement (see log below).

**To Reproduce**  
Probably hard to reproduce but I try to give the needed details.
This is what I have in an HTML module in my vis:
```
<div id="warningList" class="empty" style="color:white;"></div>

<script>
var warnings =             {javascript.0.myObjects.warnings.batteryWarnings};
warnings = warnings.concat({javascript.0.myObjects.warnings.co2Warnings});
warnings = warnings.concat({javascript.0.myObjects.warnings.dryerWarnings});
warnings = warnings.concat({javascript.0.myObjects.warnings.gruenbeckWarnings});
warnings = warnings.concat({javascript.0.myObjects.warnings.heatingBrokeWarnings});
warnings = warnings.concat({javascript.0.myObjects.warnings.humidityWarnings});
warnings = warnings.concat({javascript.0.myObjects.warnings.mailboxWarnings});
warnings = warnings.concat({javascript.0.myObjects.warnings.vacuumWarnings});
warnings = warnings.concat({javascript.0.myObjects.warnings.ventilationWarnings});
warnings = warnings.concat({javascript.0.myObjects.warnings.washingMachineWarnings});
warnings = warnings.concat({javascript.0.myObjects.warnings.weatherWarnings});
warnings = warnings.concat({javascript.0.myObjects.warnings.mowerWarnings});
warnings = warnings.concat({javascript.0.myObjects.warnings.trashWarnings});

if (warnings.length === 0) {
    $("#warningList")[0].className = "empty";
} else {
    $("#warningList")[0].className = "";
    //    $("#warningList")[0].innerHTML = "";
    for(i=0; i<warnings.length; i++) {
        var warning = document.createElement('div');
        warning.className = "warning " + warnings[i].level;
        warning.innerHTML = "<div class=\"title\">" + warnings[i].title + "<span class=\"date\">" + moment(warnings[i].date).format("DD.MM. HH:mm") + "<span></div>" + 
                            "<div class=\"content\">" + warnings[i].content + "</div>";
        $("#warningList")[0].appendChild(warning);
    }
}
</script>

```

This is the crash in the logs:
```
host.iobroker-pi4 | 2021-11-07 22:14:09.868 | error | instance system.adapter.web.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.iobroker-pi4 | 2021-11-07 22:14:09.868 | error | Caught by controller[0]: at processTicksAndRejections (internal/process/task_queues.js:79:11)
host.iobroker-pi4 | 2021-11-07 22:14:09.867 | error | Caught by controller[0]: at /opt/iobroker/node_modules/socket.io/lib/socket.js:528:12
host.iobroker-pi4 | 2021-11-07 22:14:09.867 | error | Caught by controller[0]: at Socket.EventEmitter.emit (domain.js:483:12)
host.iobroker-pi4 | 2021-11-07 22:14:09.867 | error | Caught by controller[0]: at Socket.emit (events.js:314:20)
host.iobroker-pi4 | 2021-11-07 22:14:09.867 | error | Caught by controller[0]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.socketio/lib/socket.js:1239:26)
host.iobroker-pi4 | 2021-11-07 22:14:09.867 | error | Caught by controller[0]: at IOSocket.subscribe (/opt/iobroker/node_modules/iobroker.socketio/lib/socket.js:311:46)
host.iobroker-pi4 | 2021-11-07 22:14:09.866 | error | Caught by controller[0]: at new RegExp (<anonymous>)
host.iobroker-pi4 | 2021-11-07 22:14:09.866 | error | Caught by controller[0]: /: Nothing to repeat
host.iobroker-pi4 | 2021-11-07 22:14:09.866 | error | Caught by controller[0]: </script>
host.iobroker-pi4 | 2021-11-07 22:14:09.866 | error | Caught by controller[0]: }
host.iobroker-pi4 | 2021-11-07 22:14:09.865 | error | Caught by controller[0]: }
host.iobroker-pi4 | 2021-11-07 22:14:09.865 | error | Caught by controller[0]: $\("#warningList"\)\[0\]\.appendChild\(warning\);
host.iobroker-pi4 | 2021-11-07 22:14:09.865 | error | Caught by controller[0]: "<div class=\"content\">" + warnings\[i\]\.content + "</div>";
host.iobroker-pi4 | 2021-11-07 22:14:09.865 | error | Caught by controller[0]: warning\.innerHTML = "<div class=\"title\">" + warnings\[i\]\.title + "<span class=\"date\">" + moment\(warnings\[i\]\.date\)\.format\("DD\.MM\. HH:mm"\) + "<span></div>" +
host.iobroker-pi4 | 2021-11-07 22:14:09.865 | error | Caught by controller[0]: warning\.className = "warning " + warnings\[i\]\.level;
host.iobroker-pi4 | 2021-11-07 22:14:09.864 | error | Caught by controller[0]: var warning = document\.createElement\('div'\);
host.iobroker-pi4 | 2021-11-07 22:14:09.864 | error | Caught by controller[0]: for\(i=0; i<warnings\.length; i++\) {
host.iobroker-pi4 | 2021-11-07 22:14:09.864 | error | Caught by controller[0]: // $\("#warningList"\)\[0\]\.innerHTML = "";
host.iobroker-pi4 | 2021-11-07 22:14:09.864 | error | Caught by controller[0]: $\("#warningList"\)\[0\]\.className = "";
host.iobroker-pi4 | 2021-11-07 22:14:09.863 | error | Caught by controller[0]: } else {
host.iobroker-pi4 | 2021-11-07 22:14:09.863 | error | Caught by controller[0]: $\("#warningList"\)\[0\]\.className = "empty";
host.iobroker-pi4 | 2021-11-07 22:14:09.863 | error | Caught by controller[0]: if \(warnings\.length === 0\) {
host.iobroker-pi4 | 2021-11-07 22:14:09.863 | error | Caught by controller[0]: warnings = warnings\.concat\(null\);
host.iobroker-pi4 | 2021-11-07 22:14:09.862 | error | Caught by controller[0]: warnings = warnings\.concat\(null\);
host.iobroker-pi4 | 2021-11-07 22:14:09.862 | error | Caught by controller[0]: warnings = warnings\.concat\(null\);
host.iobroker-pi4 | 2021-11-07 22:14:09.862 | error | Caught by controller[0]: warnings = warnings\.concat\(null\);
host.iobroker-pi4 | 2021-11-07 22:14:09.862 | error | Caught by controller[0]: warnings = warnings\.concat\(null\);
host.iobroker-pi4 | 2021-11-07 22:14:09.861 | error | Caught by controller[0]: warnings = warnings\.concat\(null\);
host.iobroker-pi4 | 2021-11-07 22:14:09.861 | error | Caught by controller[0]: warnings = warnings\.concat\(null\);
host.iobroker-pi4 | 2021-11-07 22:14:09.861 | error | Caught by controller[0]: warnings = warnings\.concat\(null\);
host.iobroker-pi4 | 2021-11-07 22:14:09.861 | error | Caught by controller[0]: warnings = warnings\.concat\(null\);
host.iobroker-pi4 | 2021-11-07 22:14:09.860 | error | Caught by controller[0]: warnings = warnings\.concat\(null\);
host.iobroker-pi4 | 2021-11-07 22:14:09.860 | error | Caught by controller[0]: warnings = warnings\.concat\(null\);
host.iobroker-pi4 | 2021-11-07 22:14:09.860 | error | Caught by controller[0]: warnings = warnings\.concat\(null\);
host.iobroker-pi4 | 2021-11-07 22:14:09.859 | error | Caught by controller[0]: \];
host.iobroker-pi4 | 2021-11-07 22:14:09.859 | error | Caught by controller[0]: }
host.iobroker-pi4 | 2021-11-07 22:14:09.858 | error | Caught by controller[0]: "content": "Batterie von <img src='http://192\.168\.1\.50:8081/adapter/hm-rpc/icons/102_hm-es-tx-wm_thumb\.png'/> <strong>Stromzähler</strong> neigt sich dem Ende\."
host.iobroker-pi4 | 2021-11-07 22:14:09.858 | error | Caught by controller[0]: "level": "WARN",
host.iobroker-pi4 | 2021-11-07 22:14:09.858 | error | Caught by controller[0]: "date": "2020-12-19T10:54:12\.223Z",
host.iobroker-pi4 | 2021-11-07 22:14:09.857 | error | Caught by controller[0]: "device": "hm-rpc\.0\.NEQ0862838\.0",
host.iobroker-pi4 | 2021-11-07 22:14:09.857 | error | Caught by controller[0]: "title": "Batteriewarnung",
host.iobroker-pi4 | 2021-11-07 22:14:09.857 | error | Caught by controller[0]: {
host.iobroker-pi4 | 2021-11-07 22:14:09.856 | error | Caught by controller[0]: var warnings = \[
host.iobroker-pi4 | 2021-11-07 22:14:09.856 | error | Caught by controller[0]: <script>
host.iobroker-pi4 | 2021-11-07 22:14:09.850 | error | Caught by controller[0]: SyntaxError: Invalid regular expression: /<div id="warningList" class="empty" style="color:white;"></div>
web.0 | 2021-11-07 22:14:09.677 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
web.0 | 2021-11-07 22:14:09.650 | error | Invalid regular expression: /<div id="warningList" class="empty" style="color:white;"></div> <script> var warnings = \[ { "title": "Batteriewarnung", "device": "hm-rpc\.0\.NEQ0862838\.0", "date": "2020-12-19T10:54:12\.223Z", "level": "WARN", "content": "Batterie von <img src='http://192\.168\.1\.50:8081/adapter/hm-rpc/icons/102_hm-es-tx-wm_thumb\.png'/> <strong>Stromzähler</strong> neigt sich dem Ende\." } \]; warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); if \(warnings\.length === 0\) { $\("#warningList"\)\[0\]\.className = "empty"; } else { $\("#warningList"\)\[0\]\.className = ""; // $\("#warningList"\)\[0\]\.innerHTML = ""; for\(i=0; i<warnings\.length; i++\) { var warning = document\.createElement\('div'\); warning\.className = "warning " + warnings\[i\]\.level; warning\.innerHTML = "<div class=\"title\">" + warnings\[i\]\.title + "<span class=\"date\">" + moment\(warnings\[i\]\.date\)\.format\("DD\.MM\. HH:mm"\) + "<span></div>" + "<div class=\"content\">" + warnings\[i\]\.content + "</div>"; $\("#warningList"\)\[0\]\.appendChild\(warning\); } } </script> /: Nothing to repeat
web.0 | 2021-11-07 22:14:09.649 | error | SyntaxError: Invalid regular expression: /<div id="warningList" class="empty" style="color:white;"></div> <script> var warnings = \[ { "title": "Batteriewarnung", "device": "hm-rpc\.0\.NEQ0862838\.0", "date": "2020-12-19T10:54:12\.223Z", "level": "WARN", "content": "Batterie von <img src='http://192\.168\.1\.50:8081/adapter/hm-rpc/icons/102_hm-es-tx-wm_thumb\.png'/> <strong>Stromzähler</strong> neigt sich dem Ende\." } \]; warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); if \(warnings\.length === 0\) { $\("#warningList"\)\[0\]\.className = "empty"; } else { $\("#warningList"\)\[0\]\.className = ""; // $\("#warningList"\)\[0\]\.innerHTML = ""; for\(i=0; i<warnings\.length; i++\) { var warning = document\.createElement\('div'\); warning\.className = "warning " + warnings\[i\]\.level; warning\.innerHTML = "<div class=\"title\">" + warnings\[i\]\.title + "<span class=\"date\">" + moment\(warnings\[i\]\.date\)\.format\("DD\.MM\. HH:mm"\) + "<span></div>" + "<div class=\"content\">" + warnings\[i\]\.content + "</div>"; $\("#warningList"\)\[0\]\.appendChild\(warning\); } } </script> /: Nothing to repeat at new RegExp (<anonymous>) at IOSocket.subscribe (/opt/iobroker/node_modules/iobroker.socketio/lib/socket.js:311:46) at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.socketio/lib/socket.js:1239:26) at Socket.emit (events.js:314:20) at Socket.EventEmitter.emit (domain.js:483:12) at /opt/iobroker/node_modules/socket.io/lib/socket.js:528:12 at processTicksAndRejections (internal/process/task_queues.js:79:11)
web.0 | 2021-11-07 22:14:09.647 | error | uncaught exception: Invalid regular expression: /<div id="warningList" class="empty" style="color:white;"></div> <script> var warnings = \[ { "title": "Batteriewarnung", "device": "hm-rpc\.0\.NEQ0862838\.0", "date": "2020-12-19T10:54:12\.223Z", "level": "WARN", "content": "Batterie von <img src='http://192\.168\.1\.50:8081/adapter/hm-rpc/icons/102_hm-es-tx-wm_thumb\.png'/> <strong>Stromzähler</strong> neigt sich dem Ende\." } \]; warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); warnings = warnings\.concat\(null\); if \(warnings\.length === 0\) { $\("#warningList"\)\[0\]\.className = "empty"; } else { $\("#warningList"\)\[0\]\.className = ""; // $\("#warningList"\)\[0\]\.innerHTML = ""; for\(i=0; i<warnings\.length; i++\) { var warning = document\.createElement\('div'\); warning\.className = "warning " + warnings\[i\]\.level; warning\.innerHTML = "<div class=\"title\">" + warnings\[i\]\.title + "<span class=\"date\">" + moment\(warnings\[i\]\.date\)\.format\("DD\.MM\. HH:mm"\) + "<span></div>" + "<div class=\"content\">" + warnings\[i\]\.content + "</div>"; $\("#warningList"\)\[0\]\.appendChild\(warning\); } } </script> /: Nothing to repeat

```

So the case that crashes comes for example with this replacement:

```
<script>
var warnings =             [
  {
    "title": "Batteriewarnung",
    "device": "hm-rpc.0.NEQ0862838.0",
    "date": "2020-12-19T10:54:12.223Z",
    "level": "WARN",
    "content": "Batterie von <img src='http://192.168.1.50:8081/adapter/hm-rpc/icons/102_hm-es-tx-wm_thumb.png'/> <strong>Stromzähler</strong> neigt sich dem Ende."
  }
];
warnings = warnings.concat(null);
warnings = warnings.concat(null);
warnings = warnings.concat(null);
warnings = warnings.concat(null);
warnings = warnings.concat(null);
warnings = warnings.concat(null);
warnings = warnings.concat(null);
warnings = warnings.concat(null);
warnings = warnings.concat(null);
warnings = warnings.concat(null);
warnings = warnings.concat(null);
warnings = warnings.concat(null);

if (warnings.length === 0) {
    $("#warningList")[0].className = "empty";
} else {
    $("#warningList")[0].className = "";
    //    $("#warningList")[0].innerHTML = "";
    for(i=0; i<warnings.length; i++) {
        var warning = document.createElement('div');
        warning.className = "warning " + warnings[i].level;
        warning.innerHTML = "<div class=\"title\">" + warnings[i].title + "<span class=\"date\">" + moment(warnings[i].date).format("DD.MM. HH:mm") + "<span></div>" + 
                            "<div class=\"content\">" + warnings[i].content + "</div>";
        $("#warningList")[0].appendChild(warning);
    }
}
</script>
```
The crazy thing is, that the crash is not happening if I do a little change: The line `"device": "hm-rpc.0.NEQ0862838.0",` is causing the issue and one example of a change that results in no crash anymore is by removing one of the dots in it: `"device": "hm-rpc.0NEQ0862838.0",`

**Expected behavior**  
No crash anymore. :-)
I downgraded to 1.4.4 which solves the issue for now.

**Versions:**  
 - Adapter version: 1.4.5
 - JS-Controller version: 3.3.18
 - Node version: v12.22.6
 - Operating system: raspberry

**Comment by mswiege** [comment]
@Scrounger I assume this issue comes from your change in 3f287815b04f7fb9d1dc8fcdba99cbde2b47bdb4. If I understand correctly what you are trying with your code, you check if there are oids after the replacement to replace them as well. 
I have an oid in the value of one of my variables that get inserted in my vis and I don't expect this to be replaced with a value again. Does it really makes sense to replace oids a second time? 
If so, can you adapt your regex to not crash if a plain oid is in the text and make it match only oids that are in "{}"?

**Comment by mswiege** [comment]
I fixed the issue by checking for invalid characters in the value before trying to do the Regex to match for an oid. 
See PR above.

**Comment by mswiege** [comment]
Fixed in v.1.4.7
