### ISSUE TITLE
Vis broken after upgrading admin adapter to 5.2.1

### ISSUE THREAD

**Issue by CMNiedermayer** [ioBroker/ioBroker.vis#435]
**Describe the bug**  

**To Reproduce**  
1. Upgrade admin adapter to latest version, i.e. 5.2.1
2. Try to launch vis in external window/tab
3. The following error is shown in the new window/tab
`URIError: Failed to decode param '%web_protocol%://192.168.0.105:%web_port%/vis/edit.html'
    at decodeURIComponent (<anonymous>)
    at decode_param (/opt/iobroker/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/opt/iobroker/node_modules/express/lib/router/layer.js:148:15)
    at matchLayer (/opt/iobroker/node_modules/express/lib/router/index.js:574:18)
    at next (/opt/iobroker/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/opt/iobroker/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/iobroker/node_modules/express/lib/router/index.js:317:13)
    at /opt/iobroker/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/iobroker/node_modules/express/lib/router/index.js:335:12)`

**Expected behavior**  
The vis UI should appear.

**Screenshots & Logfiles**  
There are no further logs

**Versions:**  
 - Adapter version: 1.4.5
 - JS-Controller version: 3.3.18
 - Node version: v12.22.6

**Additional context**  
n/a

**Comment by CMNiedermayer** [comment]
The issue could be resolved by restarting the Web-Server instance.
