### ISSUE TITLE
Restore of iobroker with VIS v1.4.12 causes UNCAUGHT_EXCEPTION

### ISSUE THREAD

**Issue by RP70DP** [ioBroker/ioBroker.vis#459]
Log:

```
2022-02-21 10:17:49.796  - [32minfo[39m: host.iobroker iobroker.js-controller version 4.0.12 js-controller starting
2022-02-21 10:17:49.804  - [32minfo[39m: host.iobroker Copyright (c) 2014-2022 bluefox, 2014 hobbyquaker
2022-02-21 10:17:49.805  - [32minfo[39m: host.iobroker hostname: iobroker, node: v14.19.0
2022-02-21 10:17:49.807  - [32minfo[39m: host.iobroker ip addresses: 192.168.0.202
2022-02-21 10:17:50.127  - [32minfo[39m: host.iobroker connected to Objects and States
2022-02-21 10:17:50.157  - [32minfo[39m: host.iobroker added notifications configuration of host
2022-02-21 10:17:50.271  - [32minfo[39m: host.iobroker Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
2022-02-21 10:17:50.334  - [32minfo[39m: host.iobroker 54 instances found
2022-02-21 10:17:50.441  - [32minfo[39m: host.iobroker starting 2 instances
2022-02-21 10:17:50.470  - [33mwarn[39m: host.iobroker startInstance cannot find adapter "vis@1.4.12". Try to install it... 1 attempt
2022-02-21 10:17:50.472  - [32minfo[39m: host.iobroker iobroker install vis@1.4.12 using installedFrom
2022-02-21 10:17:50.680  - [32minfo[39m: host.iobroker instance system.adapter.admin.0 started with pid 1259
2022-02-21 10:17:52.878  - [32minfo[39m: admin.0 (1259) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
2022-02-21 10:17:52.988  - [32minfo[39m: admin.0 (1259) starting. Version 5.3.0 in /opt/iobroker/node_modules/iobroker.admin, node: v14.19.0, js-controller: 4.0.12
2022-02-21 10:17:53.049  - [32minfo[39m: admin.0 (1259) requesting all states
2022-02-21 10:17:53.050  - [32minfo[39m: admin.0 (1259) requesting all objects
2022-02-21 10:17:53.494  - [32minfo[39m: admin.0 (1259) Request actual repository...
2022-02-21 10:17:54.165  - [32minfo[39m: host.iobroker Updating repository "beta" under "http://download.iobroker.net/sources-dist-latest.json"
2022-02-21 10:17:54.350  - [32minfo[39m: host.iobroker iobroker npm-install: NPM version: 6.14.16Installing iobroker.vis@1.4.12... (System call)
2022-02-21 10:17:54.704  - [32minfo[39m: host.iobroker instance system.adapter.backitup.0 started with pid 1305
2022-02-21 10:17:56.967  - [32minfo[39m: admin.0 (1259) received all objects
2022-02-21 10:17:58.206  - [32minfo[39m: admin.0 (1259) Repository received successfully.
2022-02-21 10:17:58.305  - [32minfo[39m: admin.0 (1259) http server listening on port 8081
2022-02-21 10:17:58.306  - [32minfo[39m: admin.0 (1259) Use link "http://localhost:8081" to configure.
2022-02-21 10:17:58.927  - [32minfo[39m: backitup.0 (1305) starting. Version 2.3.3 in /opt/iobroker/node_modules/iobroker.backitup, node: v14.19.0, js-controller: 4.0.12
2022-02-21 10:17:59.067  - [32minfo[39m: backitup.0 (1305) [iobroker] backup was activated at 02:00 every 1 day(s)
2022-02-21 10:17:59.159  - [32minfo[39m: backitup.0 (1305) [ccu] backup was activated at 01:30 every 3 day(s)
2022-02-21 10:18:49.379  - [32minfo[39m: host.iobroker iobroker npm-install: 
2022-02-21 10:18:49.382  - [32minfo[39m: host.iobroker iobroker npm-install: > iobroker.vis@1.4.12 install /opt/iobroker/node_modules/iobroker.vis> node main.js --install
2022-02-21 10:18:51.086  - [32minfo[39m: vis.0 (1361) starting. Version 1.4.12 in /opt/iobroker/node_modules/iobroker.vis, node: v14.19.0, js-controller: 4.0.12
2022-02-21 10:18:51.281  - [32minfo[39m: vis.0 (1361) vis license is OK.
2022-02-21 10:18:51.851  - [31merror[39m: vis.0 (1361) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-02-21 10:18:51.853  - [31merror[39m: vis.0 (1361) unhandled promise rejection: Not exists
2022-02-21 10:18:51.857  - [31merror[39m: vis.0 (1361) Error: Not exists
    at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2961:17)
    at ObjectsInRedisClient._readFile (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:1042:26)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:1091:29)
    at processImmediate (internal/timers.js:466:21)
2022-02-21 10:18:51.858  - [31merror[39m: vis.0 (1361) Not exists
2022-02-21 10:18:52.364  - [32minfo[39m: vis.0 (1361) terminating
2022-02-21 10:18:52.366  - [33mwarn[39m: vis.0 (1361) Terminated (UNCAUGHT_EXCEPTION): Without reason
```

**Comment by latzi0710** [comment]
same here, vis version 1.4.14:

sorry for the following code, i can´t get it formated - please forgive and hints are welcome (regarding the add code-function "<>")

```
2022-04-06 19:56:19.047 - info: host.ioBroker "system.adapter.vis.0" enabled
2022-04-06 19:56:19.186 - warn: host.ioBroker startInstance cannot find adapter "vis@1.4.14". Try to install it... 1 attempt
2022-04-06 19:56:19.186 - info: host.ioBroker iobroker install vis@1.4.14 using installedFrom
2022-04-06 19:56:21.169 - info: host.ioBroker iobroker npm-install: NPM version: 6.14.15
2022-04-06 19:56:21.174 - info: host.ioBroker iobroker npm-install: Installing iobroker.vis@1.4.14... (System call)
2022-04-06 19:56:42.250 - info: host.ioBroker iobroker npm-install: > iobroker.vis@1.4.14 install /opt/iobroker/node_modules/iobroker.vis> node main.js --install
2022-04-06 19:56:43.444 - info: vis.0 (3690083) starting. Version 1.4.14 in /opt/iobroker/node_modules/iobroker.vis, node: v14.18.2, js-controller: 4.0.21
2022-04-06 19:56:43.651 - info: vis.0 (3690083) vis license is OK.
2022-04-06 19:56:43.876 - error: vis.0 (3690083) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-04-06 19:56:43.877 - error: vis.0 (3690083) unhandled promise rejection: Not exists
2022-04-06 19:56:43.878 - error: vis.0 (3690083) Error: Not exists
at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2973:17)
at ObjectsInRedisClient._readFile (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:1043:26)
at Immediate. (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:1092:29)
at processImmediate (internal/timers.js:466:21)
2022-04-06 19:56:43.879 - error: vis.0 (3690083) Not exists
2022-04-06 19:56:44.383 - info: vis.0 (3690083) terminating
2022-04-06 19:56:44.384 - warn: vis.0 (3690083) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-04-06 19:56:47.237 - error: host.ioBroker iobroker npm-install: host.ioBroker Cannot install iobroker.vis@1.4.14: 6
2022-04-06 19:56:48.257 - info: host.ioBroker iobroker npm-install: exit 25
2022-04-06 19:56:49.257 - warn: host.ioBroker startInstance cannot find adapter "vis@1.4.14". Try to install it... 2 attempt
2022-04-06 19:56:49.258 - info: host.ioBroker iobroker install vis@1.4.14 using installedFrom
2022-04-06 19:56:51.018 - info: host.ioBroker iobroker npm-install: NPM version: 6.14.15
2022-04-06 19:56:51.020 - info: host.ioBroker iobroker npm-install: Installing iobroker.vis@1.4.14... (System call)
2022-04-06 19:57:11.439 - info: host.ioBroker iobroker npm-install: > iobroker.vis@1.4.14 install /opt/iobroker/node_modules/iobroker.vis> node main.js --install
2022-04-06 19:57:12.701 - info: vis.0 (3690125) starting. Version 1.4.14 in /opt/iobroker/node_modules/iobroker.vis, node: v14.18.2, js-controller: 4.0.21
2022-04-06 19:57:12.897 - info: vis.0 (3690125) vis license is OK.
2022-04-06 19:57:13.154 - error: vis.0 (3690125) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-04-06 19:57:13.155 - error: vis.0 (3690125) unhandled promise rejection: Not exists
2022-04-06 19:57:13.157 - error: vis.0 (3690125) Error: Not exists
at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2973:17)
at ObjectsInRedisClient._readFile (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:1043:26)
at Immediate. (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:1092:29)
at processImmediate (internal/timers.js:466:21)
2022-04-06 19:57:13.157 - error: vis.0 (3690125) Not exists
2022-04-06 19:57:13.664 - info: vis.0 (3690125) terminating
2022-04-06 19:57:13.665 - warn: vis.0 (3690125) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-04-06 19:57:16.419 - error: host.ioBroker iobroker npm-install: host.ioBroker Cannot install iobroker.vis@1.4.14: 6
2022-04-06 19:57:17.441 - info: host.ioBroker iobroker npm-install: exit 25
2022-04-06 19:57:18.441 - warn: host.ioBroker startInstance cannot find adapter "vis@1.4.14". Try to install it... 3 attempt
2022-04-06 19:57:18.442 - info: host.ioBroker iobroker install vis@1.4.14 using installedVersion
2022-04-06 19:57:20.261 - info: host.ioBroker iobroker npm-install: NPM version: 6.14.15
2022-04-06 19:57:20.262 - info: host.ioBroker iobroker npm-install: Installing iobroker.vis@1.4.14... (System call)
2022-04-06 19:57:40.309 - info: host.ioBroker iobroker npm-install:
2022-04-06 19:57:40.310 - info: host.ioBroker iobroker npm-install: > iobroker.vis@1.4.14 install /opt/iobroker/node_modules/iobroker.vis> node main.js --install
2022-04-06 19:57:41.574 - info: vis.0 (3690167) starting. Version 1.4.14 in /opt/iobroker/node_modules/iobroker.vis, node: v14.18.2, js-controller: 4.0.21
2022-04-06 19:57:41.775 - info: vis.0 (3690167) vis license is OK.
2022-04-06 19:57:42.043 - error: vis.0 (3690167) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-04-06 19:57:42.043 - error: vis.0 (3690167) unhandled promise rejection: Not exists
2022-04-06 19:57:42.045 - error: vis.0 (3690167) Error: Not exists
at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2973:17)
at ObjectsInRedisClient._readFile (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:1043:26)
at Immediate. (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:1092:29)
at processImmediate (internal/timers.js:466:21)
2022-04-06 19:57:42.045 - error: vis.0 (3690167) Not exists
2022-04-06 19:57:42.552 - info: vis.0 (3690167) terminating
2022-04-06 19:57:42.553 - warn: vis.0 (3690167) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-04-06 19:57:45.175 - error: host.ioBroker iobroker npm-install: host.ioBroker Cannot install iobroker.vis@1.4.14: 6
2022-04-06 19:57:46.190 - info: host.ioBroker iobroker npm-install: exit 25
2022-04-06 19:57:47.191 - warn: host.ioBroker startInstance cannot find adapter "vis@1.4.14". Try to install it... 4 attempt
2022-04-06 19:57:47.192 - info: host.ioBroker iobroker install vis@1.4.14 using installedVersion
2022-04-06 19:57:49.047 - info: host.ioBroker iobroker npm-install: NPM version: 6.14.15
2022-04-06 19:57:49.048 - info: host.ioBroker iobroker npm-install: Installing iobroker.vis@1.4.14... (System call)
2022-04-06 19:58:09.402 - info: host.ioBroker iobroker npm-install: > iobroker.vis@1.4.14 install /opt/iobroker/node_modules/iobroker.vis> node main.js --install
2022-04-06 19:58:10.633 - info: vis.0 (3690209) starting. Version 1.4.14 in /opt/iobroker/node_modules/iobroker.vis, node: v14.18.2, js-controller: 4.0.21
2022-04-06 19:58:10.836 - info: vis.0 (3690209) vis license is OK.
2022-04-06 19:58:11.091 - error: vis.0 (3690209) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-04-06 19:58:11.092 - error: vis.0 (3690209) unhandled promise rejection: Not exists
2022-04-06 19:58:11.093 - error: vis.0 (3690209) Error: Not exists
at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2973:17)
at ObjectsInRedisClient._readFile (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:1043:26)
at Immediate. (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:1092:29)
at processImmediate (internal/timers.js:466:21)
2022-04-06 19:58:11.094 - error: vis.0 (3690209) Not exists
2022-04-06 19:58:11.600 - info: vis.0 (3690209) terminating
2022-04-06 19:58:11.601 - warn: vis.0 (3690209) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-04-06 19:58:14.315 - error: host.ioBroker iobroker npm-install: host.ioBroker Cannot install iobroker.vis@1.4.14: 6
2022-04-06 19:58:15.334 - info: host.ioBroker iobroker npm-install: exit 25
2022-04-06 19:58:16.334 - error: host.ioBroker Cannot download and install adapter "vis@1.4.14". To retry it disable/enable the adapter or restart host. Also check the error messages in the log!
```

**Edit: solved, after "iobroker install vis@1.4.5" no error occured and vis was installed correctly. Following update to 1.4.14 without any problems or errors.**

**Comment by RP70DP** [comment]
Stay open.

**Comment by mcm1957** [comment]
Could be related to https://github.com/ioBroker/ioBroker.vis/issues/805 and https://github.com/ioBroker/ioBroker.vis/pull/806.

File js/config.js seems not to be restored from backup. This might need another fix if the restauration is desired.

**Comment by Apollon77** [comment]
> File js/config.js seems not to be restored from backup.

But this would maybe be a bigger topic because then the location needs to be changed into a meta.user area..
