### ISSUE TITLE
Error starting VIS after Restore: Not exists at Object.maybeCallbackWithError

### ISSUE THREAD

**Issue by gitknd** [ioBroker/ioBroker.vis#476]
I did a restore on my docker/synology iobroker installation.
All adapter are up to date
First, i've got an error while automatically installing vis 1.4.14
npm i iobroker.vis@1.4.14 (and then npm i iobroker.vis@1.4.15) in the console solved this.
But before this error above and also still now, i get this error:
<html>
<body>

host.iobroker | 2022-04-12 07:31:06.044 | info | instance system.adapter.vis.0 terminated while should be started once
-- | -- | -- | --
vis.0 | 2022-04-12 07:31:05.436 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
vis.0 | 2022-04-12 07:31:05.435 | info | terminating
vis.0 | 2022-04-12 07:31:04.928 | error | Not exists
vis.0 | 2022-04-12 07:31:04.928 | error | Error: Not exists at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2973:17) at ObjectsInRedisClient._readFile (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:1043:26) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:1092:29) at processImmediate (internal/timers.js:466:21)
vis.0 | 2022-04-12 07:31:04.925 | error | unhandled promise rejection: Not exists
vis.0 | 2022-04-12 07:31:04.924 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
vis.0 | 2022-04-12 07:31:04.409 | info | vis license is OK.
vis.0 | 2022-04-12 07:31:04.185 | info | starting. Version 1.4.15 in /opt/iobroker/node_modules/iobroker.vis, node: v14.19.1, js-controller: 4.0.21

</body>
</html>

**Comment by gitknd** [comment]
update:
installing vis 1.4.5 and back to 1.4.15 plus "iob upload vis" solved it
(https://forum.iobroker.net/topic/54014/gel%C3%B6st-vis-uncaught-exception-nach-backitup-restore/5)
