### ISSUE TITLE
VIS lässt sich nicht installieren

### ISSUE THREAD

**Issue by denjo1982** [ioBroker/ioBroker.vis#502]
Vis lässt sich nicht installieren???

`<html>
<body>

Quelle | PID | Zeit | error | Nachricht
-- | -- | -- | -- | --
host.raspberrypi |   | 2022-06-12 15:03:15.666 | error | iobroker host.raspberrypi Cannot install iobroker/ioBroker.vis: 6
vis.0 | 27657 | 2022-06-12 15:03:14.369 | error | Not exists
vis.0 | 27657 | 2022-06-12 15:03:14.368 | error | Error: Not exists at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2973:17) at ObjectsInRedisClient._readFile (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:1043:26) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:1092:29) at processImmediate (node:internal/timers:468:21)
vis.0 | 27657 | 2022-06-12 15:03:14.365 | error | unhandled promise rejection: Not exists
vis.0 | 27657 | 2022-06-12 15:03:14.363 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>`

**Comment by Apollon77** [comment]
welcher js-controller?

**Comment by denjo1982** [comment]
16.15.1

**Comment by denjo1982** [comment]
4.0.23

**Comment by denjo1982** [comment]
habe den fehler gefunden, es liegt daran das ich auf 64bit gewechselt bin

**Comment by Apollon77** [comment]
Hast Du mehr Details?

**Comment by crunchip77** [comment]
@Apollon77
 ich habe ein backup eingespielt, nachdem ich den kompletten iobroker gelöscht und neu installiert habe. Im Forum weise ich extra darauf hin und selbst Natürlich vergessen vis zuvor zu installieren, also die Variante mit einer alten Version versucht, jedoch kommt selbiger Fehler mit v1.4.15, v1.4.12, v1.4.8

`
<html>
<body>


2022-07-12 21:18:51.480 - info: vis.0 (45646) starting. Version 1.4.15 in /opt/iobroker/node_modules/iobroker.vis, node: v16.16.0, js-controller: 4.0.23
--
2022-07-12 21:18:51.697 - info: vis.0 (45646) vis license is OK.
2022-07-12 21:18:52.396 - error: vis.0 (45646) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-07-12 21:18:52.397 - error: vis.0 (45646) unhandled promise rejection: Not exists
2022-07-12 21:18:52.399 - error: vis.0 (45646) Error: Not exists
at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2973:17)
at ObjectsInRedisClient._readFile (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:1043:26)
at Immediate. (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:1092:29)
at processImmediate (node:internal/timers:468:21)
2022-07-12 21:18:52.401 - error: vis.0 (45646) Not exists
2022-07-12 21:18:52.916 - info: vis.0 (45646) terminating
2022-07-12 21:18:52.918 - warn: vis.0 (45646) Terminated (UNCAUGHT_EXCEPTION): Without reason


</body>
</html>

`

Auszug Konsole

`
BE CAREFUL: THIS IS A MAJOR UPGRADE, WHICH WILL MOST LIKELY INTRODUCE BREAKING CHANGES!
Would you like to upgrade vis from @0.0.0 to @1.4.12 now? [(y)es, (n)o]: y
Update vis from @0.0.0 to @1.4.12
NPM version: 8.11.0
Installing iobroker.vis@1.4.12... (System call)
npm ERR! code 6
npm ERR! path /opt/iobroker/node_modules/iobroker.vis
npm ERR! command failed
npm ERR! command sh -c node main.js --install

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2022-07-12T19_13_47_984Z-debug-0.log
host.IoBroker Cannot install iobroker.vis@1.4.12: 6
`

hab es dann mit 1.4.0 versucht und die wurde erfolgreich installiert, vllt hilft es ja, das Problem weiter einzugrenzen
