### ISSUE TITLE
Icons lassen sich im VIS Editor nicht löschen

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.vis#538]
Icon Bilder die über den Dateimanager des VIS Editor (1.4.15) versucht werden zu löschen, enden darin, das der VIS Editor einen Verbindungsfehler anzeigt.

![image](https://user-images.githubusercontent.com/44617472/197410577-2cb48bab-bf52-434e-ba20-612f4fd218cc.png)

PlatformBetriebssystem:win32
Architektur:x64
CPUs:4
Geschwindigkeit:1995 MHz
Modell:Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
RAM:7.9 GB
System-Betriebszeit:00:00:00
Node.js:v14.16.0
time:1666534876354
timeOffset:-120
Adapter-Anzahl:531
NPM:6.14.11
Datenträgergröße:118.1 GB
Freier Festplattenspeicher:21.0 GB
Betriebszeit:2 T. 22:52:35
Aktive Instanzen:43
Pfad:C:\iobroker\GLT\
aktiv:true
_nodeCurrent:14.16.0
_nodeNewest:14.20.1
_nodeNewestNext:16.18.0
_npmCurrent:6.14.11
_npmNewest:6.14.11
_npmNewestNext:8.19.2

Anbei die entsprechende Fehlermeldung im Admin LOG

<html>
<body>

host.GLTGLT) |   | 2022-10-23 16:17:25.032 | error | host.GLT(GLT) instance system.adapter.web.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | -- | --
host.GLTGLT) |   | 2022-10-23 16:17:25.032 | error | host.GLT(GLT) Caught by controller[0]: at parseType (C:\iobroker\GLT\node_modules\redis-parser\lib\parser.js:302:14)
host.GLTGLT) |   | 2022-10-23 16:17:25.032 | error | host.GLT(GLT) Caught by controller[0]: at parseError (C:\iobroker\GLT\node_modules\redis-parser\lib\parser.js:179:12)
host.GLTGLT) |   | 2022-10-23 16:17:25.031 | error | host.GLT(GLT) Caught by controller[0]: ReplyError: Error ERROR readDir id=vis.0: ENOTDIR: not a directory, scandir 'C:\iobroker\GLT\iobroker-data\files\vis.0\main\icons\tuer_offen.png\'
web.0 | 12124 | 2022-10-23 16:17:24.837 | error | Error ERROR readDir id=vis.0: ENOTDIR: not a directory, scandir 'C:\iobroker\GLT\iobroker-data\files\vis.0\main\icons\tuer_offen.png\'
web.0 | 12124 | 2022-10-23 16:17:24.836 | error | ReplyError: Error ERROR readDir id=vis.0: ENOTDIR: not a directory, scandir 'C:\iobroker\GLT\iobroker-data\files\vis.0\main\icons\tuer_offen.png\' at parseError (C:\iobroker\GLT\node_modules\redis-parser\lib\parser.js:179:12) at parseType (C:\iobroker\GLT\node_modules\redis-parser\lib\parser.js:302:14)
web.0 | 12124 | 2022-10-23 16:17:24.832 | error | uncaught exception: Error ERROR readDir id=vis.0: ENOTDIR: not a directory, scandir 'C:\iobroker\GLT\iobroker-data\files\vis.0\main\icons\tuer_offen.png\'
host.GLTGLT)-Server |   | 2022-10-23 16:17:24.821 | warn | host.GLT(GLT)-Server Objects 127.0.0.1:53868 Error from InMemDB: Error: ERROR readDir id=vis.0: ENOTDIR: not a directory, scandir 'C:\iobroker\GLT\iobroker-data\files\vis.0\main\icons\tuer_offen.png\'
 

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by Apollon77** [comment]
Naja irgendwas stimmt da nicht. Der Fehler sagt das es das Verzeichnis nicht gibt. Ist das denn so?

Ansonsten bitte "iob file sync" einmal bei beendetem ioBroker aufrufen. Das sollte falls was out of sync ist.

**Comment by JBSullivan** [comment]
> Naja irgendwas stimmt da nicht. Der Fehler sagt das es das Verzeichnis nicht gibt. Ist das denn so?

Nein das ist natürlich nicht so

![image](https://user-images.githubusercontent.com/44617472/197469626-9160d7ee-bae4-4965-91dd-b1f243ab6536.png)

Sicher das dass der richtige Befehl ist?

`C:\iobroker\GLT>iob file sync
File Sync is only available when database type "file" is used.`

**Comment by Apollon77** [comment]
> C:\iobroker\GLT>iob file sync File Sync is only available when database type "file" is used.

Mist haben wir was vergessen bei jsonl ... Bitte leg mal ein js.controller issue an. Muss auch bei jsonl gehen

**Comment by Apollon77** [comment]
Ok, dann denkt er trotzdem da es ein Verzeichnis ist - ist aber ein File ...  Komisch.
