### ISSUE TITLE
Vis2.x SimpleClock Uhrzeit steht

### ISSUE THREAD

**Issue by mrjeschke** [ioBroker/ioBroker.vis#560]
Uhrzeit wird nur beim Start der vis aktuallisiert, danach steht die Uhrzeit.
Widget wird auch an falscher Position angezeigt.
vis 			v2.0.7
timeandweather	v.1.2.2

`
<html>
<body>

2022-11-26 16:42:22.664 - error: web.0 (404) can't render tplTwSimpleClock w000159 on "Test":
--
2022-11-26 16:42:22.665 - error: web.0 (404) 0 - ReferenceError: _setTimeout is not definedReferenceError: _setTimeout is not defined
2022-11-26 16:42:22.665 - error: web.0 (404) 1 - at Object.startTime (:170:17)
2022-11-26 16:42:22.665 - error: web.0 (404) 2 - at Object.eval (tplTwSimpleClock.js:3:34)
2022-11-26 16:42:22.665 - error: web.0 (404) 3 - at n.render (http://172.16.4.181:8082/vis-2-beta/lib/js/can.custom.js:2229:46)
2022-11-26 16:42:22.665 - error: web.0 (404) 4 - at t.template.fn (http://172.16.4.181:8082/vis-2-beta/lib/js/can.custom.js:2223:26)
2022-11-26 16:42:22.665 - error: web.0 (404) 5 - at r (http://172.16.4.181:8082/vis-2-beta/lib/js/can.custom.js:1370:29)
2022-11-26 16:42:22.665 - error: web.0 (404) 6 - at Function.renderTo (http://172.16.4.181:8082/vis-2-beta/lib/js/can.custom.js:1449:63)
2022-11-26 16:42:22.665 - error: web.0 (404) 7 - at Function.renderAs (http://172.16.4.181:8082/vis-2-beta/lib/js/can.custom.js:1465:39)
2022-11-26 16:42:22.665 - error: web.0 (404) 8 - at e.view.e.template (http://172.16.4.181:8082/vis-2-beta/lib/js/can.custom.js:1401:47)
2022-11-26 16:42:22.665 - error: web.0 (404) 9 - at Qe.renderWidget (http://172.16.4.181:8082/vis-2-beta/static/js/363.1c471ab3.chunk.js:16:67700)
2022-11-26 16:42:22.665 - error: web.0 (404) 10 - at Qe.componentDidMount (http://172.16.4.181:8082/vis-2-beta/static/js/363.1c471ab3.chunk.js:16:51349)

</body>
</html>
`

**Comment by Feuer-sturm** [comment]
@mrjeschke Please check with vis2 v2.0.8

**Comment by mrjeschke** [comment]
Sieht gut aus. Danke
