### ISSUE TITLE
Vis2 Materialdesign Widget Line History Chart keine Daten

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.vis#581]
Hallo, beim Materialdesign Widget Line History Chart kommen keine Daten.

![Screenshot (5138)](https://user-images.githubusercontent.com/41079106/204232739-0ab1e007-9e67-459d-b105-48fad157cde2.png)

`<html>
<body>

2022-11-28 08:25:16.931	error	15 - at sentryWrapped (http://localhost:8082/vis-2-beta/widgets/materialdesign/lib/raw/sentry/bundle.min.js:2:53837)
--
  |  
  | web.0
  | 2022-11-28 08:25:16.929	error	14 - at http://localhost:8082/vis-2-beta/static/js/720.4ad6ca16.chunk.js:17:458
  |  
  | web.0
  | 2022-11-28 08:25:16.929	error	13 - at Qe.renderWidget (http://localhost:8082/vis-2-beta/static/js/720.4ad6ca16.chunk.js:16:68581)
  |  
  | web.0
  | 2022-11-28 08:25:16.928	error	12 - at e.view.e.template (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:1401:47)
  |  
  | web.0
  | 2022-11-28 08:25:16.927	error	11 - at Function.renderAs (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:1465:39)
  |  
  | web.0
  | 2022-11-28 08:25:16.926	error	10 - at Function.renderTo (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:1449:63)
  |  
  | web.0
  | 2022-11-28 08:25:16.925	error	9 - at r (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:1370:22)
  |  
  | web.0
  | 2022-11-28 08:25:16.925	error	8 - at Function.frag (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:1405:22)
  |  
  | web.0
  | 2022-11-28 08:25:16.925	error	7 - at Function.hookup (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:1418:19)
  |  
  | web.0
  | 2022-11-28 08:25:16.924	error	6 - at a.each (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:343:211)
  |  
  | web.0
  | 2022-11-28 08:25:16.924	error	5 - at HTMLDivElement.<anonymous> (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:1419:98)
  |  
  | web.0
  | 2022-11-28 08:25:16.923	error	4 - at http://localhost:8082/vis-2-beta/lib/js/can.custom.js:1727:17
  |  
  | web.0
  | 2022-11-28 08:25:16.923	error	3 - at a.each (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:343:211)
  |  
  | web.0
  | 2022-11-28 08:25:16.922	error	2 - at Function.<anonymous> (http://localhost:8082/vis-2-beta/lib/js/can.custom.js:1728:17)
  |  
  | web.0
  | 2022-11-28 08:25:16.922	error	1 - at Object.eval (tplMfdSocket.js:54:65)
  |  
  | web.0
  | 2022-11-28 08:25:16.921	error	0 - TypeError: vis.preloadImages is not a functionTypeError: vis.preloadImages is not a function
  | {1}
  | web.0
  | 2022-11-28 08:25:16.920	error	can't render tplMfdSocket w00935 on "Yamaha_RX-V481":

</body>
</html>`

Plattform: Windows
RAM: 16 GB 
NODE.JS: V16.18.1
NPM: 8.19.2
JS Controller: 4.0.23
Admin: 6.2.23
WS: 2.3.1
WEB: 5.3.1
Socket.io: 6.3.1
Script Engine: 6.1.4
IOT: 1.12.5
VIS: 1.4.15
VIS2. 2.0.8

**Comment by ice987987** [comment]
which version of https://github.com/Scrounger/ioBroker.vis-materialdesign is installed: 0.5.9 or 0.5.94?

**Comment by sigi2345** [comment]
> which version of https://github.com/Scrounger/ioBroker.vis-materialdesign is installed: 0.5.9 or 0.5.94?

0.5.93
