### ISSUE TITLE
Elements in VIS Runtime are loading very slow

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.vis#582]
**Describe the bug**  
VIS1 Project was exported and imported in VIS2
If VIS Runtime is started or the URL of VIS is called some elements are just in time visible and other elements needs a few seconds to be loaded (see animation)
Tested with Firefox and Chrome Browser

If I open the same project with VIS1 all elements are available just in time and there is no delay.

**Expected behavior**  
No delay in showing different elements in VIS Runtime

**Screenshots & Logfiles**  
![Animation](https://user-images.githubusercontent.com/25422320/204363400-fd20e962-d819-457b-a00e-aec943b23193.gif)

**Versions:**  
 - Adapter version: vis-2-beta: v2.0.8

### Browser Console Output vom Aufruf der Startseite

```
iobroker.vis-2-beta@2.0.8 using theme "dark" bootstrap.jsx:20:8

██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
Prompt.js:15:12
Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters Prompt.js:16:12
Help us to create open source project with reactJS! Prompt.js:17:12
See you :) Prompt.js:18:12
[2022-11-28T19:28:30.009Z] Try to connect socket.io.js:66:41
Version vis-history: 1.0.0 vis-2-beta:75:25
Uncaught SyntaxError: missing } after function body
info.js:84note: { opened at line 9, column 31info.js:9:31
Version vis-jqui-mfd: 1.0.12 vis-2-beta:110:21
Version justgage: 1.0.2 justgage.js:115:21
Version vis-map: 1.0.3 vis-2-beta:45:25
Metro version: "1.2.0" vis-2-beta:645:10
Version trashschedule: 2.0.3 trashschedule.js:152:21
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools lib.min.js:43:9053
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html lib.min.js:43:9256
Version vis-materialdesign: 0.5.9 materialdesign.js:33:25
GEThttp://192.168.178.77:8082/vis-2-beta/widgets/vis-2-widgets-material/customWidgets.js
[HTTP/1.1 404 Not Found 55ms]

GEThttp://192.168.178.77:8082/vis-2-beta/widgets/vis-2-widgets-gauges/customWidgets.js
[HTTP/1.1 404 Not Found 53ms]

GEThttp://192.168.178.77:8082/vis-2-beta/widgets/vis-2-widgets-energy/customWidgets.js
[HTTP/1.1 404 Not Found 56ms]

GEThttp://192.168.178.77:8082/vis-2-beta/widgets/openweathermap/customWidgets.js
[HTTP/1.1 404 Not Found 56ms]

Laden fehlgeschlagen für das <script> mit der Quelle "http://192.168.178.77:8082/vis-2-beta/widgets/vis-2-widgets-material/customWidgets.js". vis-2-beta:1:1
Cannot load i18n "vis2materialWidgets": Error: Cannot load vis2materialWidgets from ./widgets/vis-2-widgets-material/customWidgets.js visUtils.jsx:848:52
Error: Cannot load vis2materialWidgets from ./widgets/vis-2-widgets-material/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
    promise callback*kt visUtils.jsx:766
    collectRxInformation visWidgetsCatalog.jsx:29
    setTimeout handler*54720/collectRxInformation/< visWidgetsCatalog.jsx:28
    collectRxInformation visWidgetsCatalog.jsx:27
    onWidgetsLoaded App.jsx:1641
    ye 720.4ad6ca16.chunk.js:33
    ye 720.4ad6ca16.chunk.js:33
    onWidgetsLoaded App.jsx:1638
    onLoaded App.jsx:1712
    loadWidgets visEngine.jsx:1166
    o 720.4ad6ca16.chunk.js:29
visUtils.jsx:868:56
Error: Cannot load vis2materialWidgets from ./widgets/vis-2-widgets-material/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
    promise callback*kt visUtils.jsx:766
    collectRxInformation visWidgetsCatalog.jsx:29
    setTimeout handler*54720/collectRxInformation/< visWidgetsCatalog.jsx:28
    collectRxInformation visWidgetsCatalog.jsx:27
    onWidgetsLoaded App.jsx:1641
    ye 720.4ad6ca16.chunk.js:33
    ye 720.4ad6ca16.chunk.js:33
    onWidgetsLoaded App.jsx:1638
    onLoaded App.jsx:1712
    loadWidgets visEngine.jsx:1166
    o 720.4ad6ca16.chunk.js:29
visUtils.jsx:868:56
Error: Cannot load vis2materialWidgets from ./widgets/vis-2-widgets-material/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
    promise callback*kt visUtils.jsx:766
    collectRxInformation visWidgetsCatalog.jsx:29
    setTimeout handler*54720/collectRxInformation/< visWidgetsCatalog.jsx:28
    collectRxInformation visWidgetsCatalog.jsx:27
    onWidgetsLoaded App.jsx:1641
    ye 720.4ad6ca16.chunk.js:33
    ye 720.4ad6ca16.chunk.js:33
    onWidgetsLoaded App.jsx:1638
    onLoaded App.jsx:1712
    loadWidgets visEngine.jsx:1166
    o 720.4ad6ca16.chunk.js:29
visUtils.jsx:868:56
Error: Cannot load vis2materialWidgets from ./widgets/vis-2-widgets-material/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
    promise callback*kt visUtils.jsx:766
    collectRxInformation visWidgetsCatalog.jsx:29
    setTimeout handler*54720/collectRxInformation/< visWidgetsCatalog.jsx:28
    collectRxInformation visWidgetsCatalog.jsx:27
    onWidgetsLoaded App.jsx:1641
    ye 720.4ad6ca16.chunk.js:33
    ye 720.4ad6ca16.chunk.js:33
    onWidgetsLoaded App.jsx:1638
    onLoaded App.jsx:1712
    loadWidgets visEngine.jsx:1166
    o 720.4ad6ca16.chunk.js:29
visUtils.jsx:868:56
Error: Cannot load vis2materialWidgets from ./widgets/vis-2-widgets-material/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
    promise callback*kt visUtils.jsx:766
    collectRxInformation visWidgetsCatalog.jsx:29
    setTimeout handler*54720/collectRxInformation/< visWidgetsCatalog.jsx:28
    collectRxInformation visWidgetsCatalog.jsx:27
    onWidgetsLoaded App.jsx:1641
    ye 720.4ad6ca16.chunk.js:33
    ye 720.4ad6ca16.chunk.js:33
    onWidgetsLoaded App.jsx:1638
    onLoaded App.jsx:1712
    loadWidgets visEngine.jsx:1166
    o 720.4ad6ca16.chunk.js:29
visUtils.jsx:868:56
Error: Cannot load vis2materialWidgets from ./widgets/vis-2-widgets-material/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
    promise callback*kt visUtils.jsx:766
    collectRxInformation visWidgetsCatalog.jsx:29
    setTimeout handler*54720/collectRxInformation/< visWidgetsCatalog.jsx:28
    collectRxInformation visWidgetsCatalog.jsx:27
    onWidgetsLoaded App.jsx:1641
    ye 720.4ad6ca16.chunk.js:33
    ye 720.4ad6ca16.chunk.js:33
    onWidgetsLoaded App.jsx:1638
    onLoaded App.jsx:1712
    loadWidgets visEngine.jsx:1166
    o 720.4ad6ca16.chunk.js:29
visUtils.jsx:868:56
Error: Cannot load vis2materialWidgets from ./widgets/vis-2-widgets-material/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
    promise callback*kt visUtils.jsx:766
    collectRxInformation visWidgetsCatalog.jsx:29
    setTimeout handler*54720/collectRxInformation/< visWidgetsCatalog.jsx:28
    collectRxInformation visWidgetsCatalog.jsx:27
    onWidgetsLoaded App.jsx:1641
    ye 720.4ad6ca16.chunk.js:33
    ye 720.4ad6ca16.chunk.js:33
    onWidgetsLoaded App.jsx:1638
    onLoaded App.jsx:1712
    loadWidgets visEngine.jsx:1166
    o 720.4ad6ca16.chunk.js:29
visUtils.jsx:868:56
Error: Cannot load vis2materialWidgets from ./widgets/vis-2-widgets-material/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
    promise callback*kt visUtils.jsx:766
    collectRxInformation visWidgetsCatalog.jsx:29
    setTimeout handler*54720/collectRxInformation/< visWidgetsCatalog.jsx:28
    collectRxInformation visWidgetsCatalog.jsx:27
    onWidgetsLoaded App.jsx:1641
    ye 720.4ad6ca16.chunk.js:33
    ye 720.4ad6ca16.chunk.js:33
    onWidgetsLoaded App.jsx:1638
    onLoaded App.jsx:1712
    loadWidgets visEngine.jsx:1166
    o 720.4ad6ca16.chunk.js:29
visUtils.jsx:868:56
Error: Cannot load vis2materialWidgets from ./widgets/vis-2-widgets-material/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
    promise callback*kt visUtils.jsx:766
    collectRxInformation visWidgetsCatalog.jsx:29
    setTimeout handler*54720/collectRxInformation/< visWidgetsCatalog.jsx:28
    collectRxInformation visWidgetsCatalog.jsx:27
    onWidgetsLoaded App.jsx:1641
    ye 720.4ad6ca16.chunk.js:33
    ye 720.4ad6ca16.chunk.js:33
    onWidgetsLoaded App.jsx:1638
    onLoaded App.jsx:1712
    loadWidgets visEngine.jsx:1166
    o 720.4ad6ca16.chunk.js:29
visUtils.jsx:868:56
Error: Cannot load vis2materialWidgets from ./widgets/vis-2-widgets-material/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
    promise callback*kt visUtils.jsx:766
    collectRxInformation visWidgetsCatalog.jsx:29
    setTimeout handler*54720/collectRxInformation/< visWidgetsCatalog.jsx:28
    collectRxInformation visWidgetsCatalog.jsx:27
    onWidgetsLoaded App.jsx:1641
    ye 720.4ad6ca16.chunk.js:33
    ye 720.4ad6ca16.chunk.js:33
    onWidgetsLoaded App.jsx:1638
    onLoaded App.jsx:1712
    loadWidgets visEngine.jsx:1166
    o 720.4ad6ca16.chunk.js:29
visUtils.jsx:868:56
Error: Cannot load vis2materialWidgets from ./widgets/vis-2-widgets-material/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
    promise callback*kt visUtils.jsx:766
    collectRxInformation visWidgetsCatalog.jsx:29
    setTimeout handler*54720/collectRxInformation/< visWidgetsCatalog.jsx:28
    collectRxInformation visWidgetsCatalog.jsx:27
    onWidgetsLoaded App.jsx:1641
    ye 720.4ad6ca16.chunk.js:33
    ye 720.4ad6ca16.chunk.js:33
    onWidgetsLoaded App.jsx:1638
    onLoaded App.jsx:1712
    loadWidgets visEngine.jsx:1166
    o 720.4ad6ca16.chunk.js:29
visUtils.jsx:868:56
Error: Cannot load vis2materialWidgets from ./widgets/vis-2-widgets-material/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
    promise callback*kt visUtils.jsx:766
    collectRxInformation visWidgetsCatalog.jsx:29
    setTimeout handler*54720/collectRxInformation/< visWidgetsCatalog.jsx:28
    collectRxInformation visWidgetsCatalog.jsx:27
    onWidgetsLoaded App.jsx:1641
    ye 720.4ad6ca16.chunk.js:33
    ye 720.4ad6ca16.chunk.js:33
    onWidgetsLoaded App.jsx:1638
    onLoaded App.jsx:1712
    loadWidgets visEngine.jsx:1166
    o 720.4ad6ca16.chunk.js:29
visUtils.jsx:868:56
Error: Cannot load vis2materialWidgets from ./widgets/vis-2-widgets-material/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
    promise callback*kt visUtils.jsx:766
    collectRxInformation visWidgetsCatalog.jsx:29
    setTimeout handler*54720/collectRxInformation/< visWidgetsCatalog.jsx:28
    collectRxInformation visWidgetsCatalog.jsx:27
    onWidgetsLoaded App.jsx:1641
    ye 720.4ad6ca16.chunk.js:33
    ye 720.4ad6ca16.chunk.js:33
    onWidgetsLoaded App.jsx:1638
    onLoaded App.jsx:1712
    loadWidgets visEngine.jsx:1166
    o 720.4ad6ca16.chunk.js:29
visUtils.jsx:868:56
Laden fehlgeschlagen für das <script> mit der Quelle "http://192.168.178.77:8082/vis-2-beta/widgets/vis-2-widgets-gauges/customWidgets.js". vis-2-beta:1:1
Cannot load i18n "vis2gaugeWidgets": Error: Cannot load vis2gaugeWidgets from ./widgets/vis-2-widgets-gauges/customWidgets.js visUtils.jsx:848:52
Error: Cannot load vis2gaugeWidgets from ./widgets/vis-2-widgets-gauges/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
visUtils.jsx:868:56
Error: Cannot load vis2gaugeWidgets from ./widgets/vis-2-widgets-gauges/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
visUtils.jsx:868:56
Error: Cannot load vis2gaugeWidgets from ./widgets/vis-2-widgets-gauges/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
visUtils.jsx:868:56
Laden fehlgeschlagen für das <script> mit der Quelle "http://192.168.178.77:8082/vis-2-beta/widgets/vis-2-widgets-energy/customWidgets.js". vis-2-beta:1:1
Cannot load i18n "vis2energyWidgets": Error: Cannot load vis2energyWidgets from ./widgets/vis-2-widgets-energy/customWidgets.js visUtils.jsx:848:52
Error: Cannot load vis2energyWidgets from ./widgets/vis-2-widgets-energy/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
visUtils.jsx:868:56
Error: Cannot load vis2energyWidgets from ./widgets/vis-2-widgets-energy/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
visUtils.jsx:868:56
Error: Cannot load vis2energyWidgets from ./widgets/vis-2-widgets-energy/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
visUtils.jsx:868:56
Error: Cannot load vis2energyWidgets from ./widgets/vis-2-widgets-energy/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
visUtils.jsx:868:56
Laden fehlgeschlagen für das <script> mit der Quelle "http://192.168.178.77:8082/vis-2-beta/widgets/openweathermap/customWidgets.js". vis-2-beta:1:1
Cannot load i18n "openweathermap": Error: Cannot load openweathermap from ./widgets/openweathermap/customWidgets.js visUtils.jsx:848:52
Error: Cannot load openweathermap from ./widgets/openweathermap/customWidgets.js
    onerror visUtils.jsx:738
    EventHandlerNonNull* visUtils.jsx:738
    dt visUtils.jsx:694
    ct visUtils.jsx:752
    kt visUtils.jsx:834
visUtils.jsx:868:56
Uncaught (in promise) TypeError: t.update is not a function
    captureSession baseclient.ts:160
    _sendSessionUpdate hub.ts:461
    captureSession hub.ts:387
    init sdk.ts:200
    init sdk.ts:94
    _initializeSentry widgets.min.js:1
    initializeSentry widgets.min.js:1
    showVersion materialdesign.js:35
    getVersion widgets.min.js:1
    getObject widgets.min.js:1
    emit visEngine.jsx:878
    promise callback*emit visEngine.jsx:878
    getObject widgets.min.js:1
    getVersion widgets.min.js:1
    showVersion materialdesign.js:32
    waitForVisConnected widgets.min.js:1
    setTimeout handler*waitForVisConnected widgets.min.js:1
    showVersion materialdesign.js:31
    <anonymous> widgets.min.js:1
baseclient.ts:160:14
[2022-11-28T19:28:36.308Z] +SUBSCRIBE: daswetter.0.NextHours.Location_1.Day_1.tempmin_value instrument.ts:129:35
[2022-11-28T19:28:36.316Z] +SUBSCRIBE: daswetter.0.NextHours.Location_1.Day_1.wind_value instrument.ts:129:35
[2022-11-28T19:28:36.347Z] +SUBSCRIBE: 0_userdata.0.daswettercom.WeatherSymbol0 instrument.ts:129:35
[2022-11-28T19:28:36.355Z] +SUBSCRIBE: daswetter.0.NextHours.Location_1.Day_1.tempmax_value instrument.ts:129:35
[2022-11-28T19:28:36.358Z] +SUBSCRIBE: daswetter.0.NextHours.Location_1.Day_1.rain_value instrument.ts:129:35
[2022-11-28T19:28:36.362Z] +SUBSCRIBE: daswetter.0.NextHours.Location_1.Day_1.symbol_desc instrument.ts:129:35
[2022-11-28T19:28:36.366Z] +SUBSCRIBE: 0_userdata.0.lueftung.AussentemperaturBerechnet instrument.ts:129:35
[2022-11-28T19:28:36.369Z] +SUBSCRIBE: 0_userdata.0.muellkalender.GrafikNaechsteTonne instrument.ts:129:35
[2022-11-28T19:28:36.370Z] +SUBSCRIBE: trashschedule.0.next.daysLeft instrument.ts:129:35
[2022-11-28T19:28:36.379Z] +SUBSCRIBE: hm-rpc.0.00241A49A769E4.1.DOOR_STATE instrument.ts:129:35
[2022-11-28T19:28:36.386Z] +SUBSCRIBE: hm-rpc.0.00241A49A769E4.1.DOOR_COMMAND instrument.ts:129:35
[2022-11-28T19:28:36.401Z] +SUBSCRIBE: 0_userdata.0.muellkalender.GrafikUeberNaechsteTonne instrument.ts:129:35
[2022-11-28T19:28:36.403Z] +SUBSCRIBE: trashschedule.0.nextAfter.daysLeft instrument.ts:129:35
[2022-11-28T19:28:36.423Z] +SUBSCRIBE: fully-tablet-control.0.device.wandtablet.state_of_charge_vis instrument.ts:129:35
[2022-11-28T19:28:36.427Z] +SUBSCRIBE: daswetter.0.NextHours.Location_1.Day_1.current.temp_value instrument.ts:129:35
[2022-11-28T19:28:36.431Z] +SUBSCRIBE: fritzbox.0.calls.ring instrument.ts:129:35
[2022-11-28T19:28:36.431Z] +SUBSCRIBE: tr-064.0.callmonitor.inbound.callerName instrument.ts:129:35
[2022-11-28T19:28:36.432Z] +SUBSCRIBE: tr-064.0.callmonitor.inbound.caller instrument.ts:129:35
[2022-11-28T19:28:36.466Z] +SUBSCRIBE: hue.0.Steckdose-Musikbox.on instrument.ts:129:35
[2022-11-28T19:28:36.468Z] +SUBSCRIBE: vis-materialdesign.0.fonts.button.default.text instrument.ts:129:35
[2022-11-28T19:28:36.468Z] +SUBSCRIBE: vis-materialdesign.0.fontSizes.button.default.text instrument.ts:129:35
[2022-11-28T19:28:36.469Z] +SUBSCRIBE: vis-materialdesign.0.colors.darkTheme instrument.ts:129:35
[2022-11-28T19:28:36.469Z] +SUBSCRIBE: vis-materialdesign.0.colors.light.button.default.primary instrument.ts:129:35
[2022-11-28T19:28:36.469Z] +SUBSCRIBE: vis-materialdesign.0.colors.dark.button.default.primary instrument.ts:129:35
[2022-11-28T19:28:36.470Z] +SUBSCRIBE: vis-materialdesign.0.colors.light.button.default.secondary instrument.ts:129:35
[2022-11-28T19:28:36.470Z] +SUBSCRIBE: vis-materialdesign.0.colors.dark.button.default.secondary instrument.ts:129:35
[2022-11-28T19:28:36.470Z] +SUBSCRIBE: vis-materialdesign.0.colors.light.button.lock_icon instrument.ts:129:35
[2022-11-28T19:28:36.471Z] +SUBSCRIBE: vis-materialdesign.0.colors.dark.button.lock_icon instrument.ts:129:35

```

### Browser Console Wether View

```
[2022-11-28T19:33:21.808Z] -UNSUBSCRIBE: daswetter.0.NextHours.Location_1.Day_1.tempmin_value instrument.ts:129:35
[2022-11-28T19:33:21.810Z] -UNSUBSCRIBE: daswetter.0.NextHours.Location_1.Day_1.wind_value instrument.ts:129:35
[2022-11-28T19:33:21.811Z] -UNSUBSCRIBE: 0_userdata.0.daswettercom.WeatherSymbol0 instrument.ts:129:35
[2022-11-28T19:33:21.812Z] -UNSUBSCRIBE: daswetter.0.NextHours.Location_1.Day_1.tempmax_value instrument.ts:129:35
[2022-11-28T19:33:21.812Z] -UNSUBSCRIBE: daswetter.0.NextHours.Location_1.Day_1.rain_value instrument.ts:129:35
[2022-11-28T19:33:21.813Z] -UNSUBSCRIBE: daswetter.0.NextHours.Location_1.Day_1.symbol_desc instrument.ts:129:35
[2022-11-28T19:33:21.814Z] -UNSUBSCRIBE: 0_userdata.0.lueftung.AussentemperaturBerechnet instrument.ts:129:35
[2022-11-28T19:33:21.814Z] -UNSUBSCRIBE: 0_userdata.0.muellkalender.GrafikNaechsteTonne instrument.ts:129:35
[2022-11-28T19:33:21.815Z] -UNSUBSCRIBE: trashschedule.0.next.daysLeft instrument.ts:129:35
[2022-11-28T19:33:21.816Z] -UNSUBSCRIBE: hm-rpc.0.00241A49A769E4.1.DOOR_STATE instrument.ts:129:35
[2022-11-28T19:33:21.816Z] -UNSUBSCRIBE: hm-rpc.0.00241A49A769E4.1.DOOR_COMMAND instrument.ts:129:35
[2022-11-28T19:33:21.817Z] -UNSUBSCRIBE: 0_userdata.0.muellkalender.GrafikUeberNaechsteTonne instrument.ts:129:35
[2022-11-28T19:33:21.817Z] -UNSUBSCRIBE: trashschedule.0.nextAfter.daysLeft instrument.ts:129:35
[2022-11-28T19:33:21.818Z] -UNSUBSCRIBE: fully-tablet-control.0.device.wandtablet.state_of_charge_vis instrument.ts:129:35
[2022-11-28T19:33:21.818Z] -UNSUBSCRIBE: daswetter.0.NextHours.Location_1.Day_1.current.temp_value instrument.ts:129:35
[2022-11-28T19:33:21.818Z] -UNSUBSCRIBE: fritzbox.0.calls.ring instrument.ts:129:35
[2022-11-28T19:33:21.818Z] -UNSUBSCRIBE: tr-064.0.callmonitor.inbound.callerName instrument.ts:129:35
[2022-11-28T19:33:21.819Z] -UNSUBSCRIBE: tr-064.0.callmonitor.inbound.caller instrument.ts:129:35
[2022-11-28T19:33:21.820Z] -UNSUBSCRIBE: hue.0.Steckdose-Musikbox.on instrument.ts:129:35
[2022-11-28T19:33:21.820Z] -UNSUBSCRIBE: vis-materialdesign.0.fonts.button.default.text instrument.ts:129:35
[2022-11-28T19:33:21.821Z] -UNSUBSCRIBE: vis-materialdesign.0.fontSizes.button.default.text instrument.ts:129:35
[2022-11-28T19:33:21.821Z] -UNSUBSCRIBE: vis-materialdesign.0.colors.darkTheme instrument.ts:129:35
[2022-11-28T19:33:21.821Z] -UNSUBSCRIBE: vis-materialdesign.0.colors.light.button.default.primary instrument.ts:129:35
[2022-11-28T19:33:21.821Z] -UNSUBSCRIBE: vis-materialdesign.0.colors.dark.button.default.primary instrument.ts:129:35
[2022-11-28T19:33:21.822Z] -UNSUBSCRIBE: vis-materialdesign.0.colors.light.button.default.secondary instrument.ts:129:35
[2022-11-28T19:33:21.822Z] -UNSUBSCRIBE: vis-materialdesign.0.colors.dark.button.default.secondary instrument.ts:129:35
[2022-11-28T19:33:21.822Z] -UNSUBSCRIBE: vis-materialdesign.0.colors.light.button.lock_icon instrument.ts:129:35
[2022-11-28T19:33:21.823Z] -UNSUBSCRIBE: vis-materialdesign.0.colors.dark.button.lock_icon instrument.ts:129:35
[2022-11-28T19:33:21.823Z] -UNSUBSCRIBE: hue.0.Weihnachten_Küche.on instrument.ts:129:35
[2022-11-28T19:33:21.824Z] -UNSUBSCRIBE: hue.0.xxx.on instrument.ts:129:35
[2022-11-28T19:33:21.824Z] -UNSUBSCRIBE: hue.0.Wohnzimmer.on instrument.ts:129:35
[2022-11-28T19:33:21.909Z] +SUBSCRIBE: javascript.0.daswettercom.ZeitstempelLeterDatenabgleich instrument.ts:129:35
[2022-11-28T19:33:21.914Z] +SUBSCRIBE: dwd.0.warning.description instrument.ts:129:35
[2022-11-28T19:33:21.918Z] +SUBSCRIBE: dwd.0.warning4.text instrument.ts:129:35
[2022-11-28T19:33:21.918Z] +SUBSCRIBE: dwd.0.warning4.severity instrument.ts:129:35
[2022-11-28T19:33:21.923Z] +SUBSCRIBE: dwd.0.warning3.text instrument.ts:129:35
[2022-11-28T19:33:21.923Z] +SUBSCRIBE: dwd.0.warning3.severity instrument.ts:129:35
[2022-11-28T19:33:21.926Z] +SUBSCRIBE: dwd.0.warning2.text instrument.ts:129:35
[2022-11-28T19:33:21.926Z] +SUBSCRIBE: dwd.0.warning2.severity instrument.ts:129:35
[2022-11-28T19:33:21.929Z] +SUBSCRIBE: dwd.0.warning1.text instrument.ts:129:35
[2022-11-28T19:33:21.929Z] +SUBSCRIBE: dwd.0.warning1.severity instrument.ts:129:35
[2022-11-28T19:33:21.932Z] +SUBSCRIBE: dwd.0.warning.text instrument.ts:129:35
[2022-11-28T19:33:21.979Z] +SUBSCRIBE: nina.0.03101.warnung01.info01.headline instrument.ts:129:35
[2022-11-28T19:33:21.982Z] +SUBSCRIBE: nina.0.03101.warnung02.info01.headline instrument.ts:129:35
[2022-11-28T19:33:21.985Z] +SUBSCRIBE: nina.0.03101.warnung03.info01.headline instrument.ts:129:35
[2022-11-28T19:33:21.988Z] +SUBSCRIBE: nina.0.03101.warnung04.info01.headline instrument.ts:129:35
[2022-11-28T19:33:21.990Z] +SUBSCRIBE: nina.0.03101.warnung05.info01.headline instrument.ts:129:35
[2022-11-28T19:33:22.019Z] +SUBSCRIBE: 0_userdata.0.daswettercom.WeatherSymbol1 instrument.ts:129:35
[2022-11-28T19:33:22.026Z] +SUBSCRIBE: 0_userdata.0.daswettercom.WeatherSymbol2 instrument.ts:129:35
GEThttp://192.168.178.77:8082/vis-2-beta/null
[HTTP/1.1 404 Not Found 433ms]

[2022-11-28T19:33:22.031Z] +SUBSCRIBE: 0_userdata.0.daswettercom.WeatherSymbol3 instrument.ts:129:35
[2022-11-28T19:33:22.035Z] +SUBSCRIBE: 0_userdata.0.daswettercom.WeatherSymbol4 instrument.ts:129:35
[2022-11-28T19:33:22.039Z] +SUBSCRIBE: 0_userdata.0.daswettercom.WeatherSymbol5 instrument.ts:129:35
Error in eval[value]: {val:rainbird.0.device.sensors.rain;val="true"? "mdui-blue-glow": " "} instrument.ts:129:35
Error in eval[script]: const val = "false";return val="true"? "mdui-blue-glow": " "; instrument.ts:129:35
Error in eval[error]: TypeError: invalid assignment to const 'val' instrument.ts:129:35
Error in eval[value]: {val:worx.0.201930198403020782E0.mower.error;val="5"? "mdui-blue-glow": " "} instrument.ts:129:35
Error in eval[script]: const val = "0";return val="5"? "mdui-blue-glow": " "; instrument.ts:129:35
Error in eval[error]: TypeError: invalid assignment to const 'val' instrument.ts:129:35
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden.
```

**Comment by Feuer-sturm** [comment]
Perhaps this issue #616 has an impact on this topic as well
