### ISSUE TITLE
Vis2 Browserlog beim öffnen der vis und neu laden der Viewesseite beim umschalten der Palette

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.vis#588]
Vis2.0.9
es sind noch keine neuen vis2 widgets installiert

Nachdem öffnen  erscheint im Browserlog
`Failed to load resource: the server responded with a status of 404 (Not Found)
VM1841:4 Uncaught TypeError: Cannot read properties of undefined (reading 'localization')
    at <anonymous>:4:39
    at Xe.<anonymous> (697.7c00624a.chunk.js:29:37779)
    at Generator.next (<anonymous>)
    at 697.7c00624a.chunk.js:29:16218
    at new Promise (<anonymous>)
    at wi (697.7c00624a.chunk.js:29:16038)
    at Xe.setInnerHTML (697.7c00624a.chunk.js:29:37201)
    at Xe.<anonymous> (697.7c00624a.chunk.js:29:38260)
    at Generator.next (<anonymous>)
    at r (697.7c00624a.chunk.js:29:16076)
widgets/info/js/info.js:84 Uncaught SyntaxError: Unexpected end of input
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/js/main.1426430e.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/js/398.c8d8d1e7.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/js/26.e8dea23d.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/js/697.7c00624a.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/js/78.756f4070.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/widgets/material-webfont/css/materialdesignicons.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/css/697.79098e54.chunk.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
3DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/widgets/material-webfont/css/materialdesignicons.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

schliest bzw öffnet man links die Palette, verschwindet die View und wird neu geladen, was mehrerer Sekunden andauert, dabei wird diese Zeile im Browserlog hochgezählt
`3DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/widgets/material-webfont/css/materialdesignicons.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

beim öffnen des Reiters materialdesign in der Palette erscheint folgendes
`VM1839:2242 Uncaught TypeError: Cannot read properties of undefined (reading 'pressed')
    at HTMLDocument.<anonymous> (<anonymous>:2242:29)
    at HTMLDocument.dispatch (jquery-1.11.2.min.js:3:8549)
    at r.handle (jquery-1.11.2.min.js:3:5252)
(anonymous) @ VM1839:2242
dispatch @ jquery-1.11.2.min.js:3
r.handle @ jquery-1.11.2.min.js:3
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/widgets/material-webfont/css/materialdesignicons.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
9Failed to decode downloaded font: <URL>
9OTS parsing error: Failed to convert WOFF 2.0 font to SFNT`

**Comment by Feuer-sturm** [comment]
@crunchip77 Can you please check if this issue is fixed with 
vis2 v2.0.18 and after updating the following adapters:
![grafik](https://user-images.githubusercontent.com/25422320/222808222-72226de0-9200-4707-ac5e-57af8bec1b87.png)

**Comment by crunchip77** [comment]
aktueller Stand, habe nun die 3 widgets installiert und vis v2.0.18
nach Aufruf der vis im Log
`<html>
<body>


web.0 | 2023-03-05 13:18:53.697 | error | 10 - at Function.renderTo (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1449:63)
-- | -- | -- | --
web.0 | 2023-03-05 13:18:53.696 | error | 9 - at r (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1370:22)
web.0 | 2023-03-05 13:18:53.694 | error | 8 - at Function.frag (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1405:22)
web.0 | 2023-03-05 13:18:53.692 | error | 7 - at Function.hookup (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1418:19)
web.0 | 2023-03-05 13:18:53.690 | error | 6 - at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
web.0 | 2023-03-05 13:18:53.688 | error | 5 - at HTMLDivElement.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1419:98)
web.0 | 2023-03-05 13:18:53.685 | error | 4 - at http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1727:17
web.0 | 2023-03-05 13:18:53.682 | error | 3 - at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
web.0 | 2023-03-05 13:18:53.678 | error | 2 - at Function.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1728:17)
web.0 | 2023-03-05 13:18:53.674 | error | 1 - at Object.eval (tplMfdShutterDialog.js:75:65)
web.0 | 2023-03-05 13:18:53.672 | error | 0 - TypeError: vis.preloadImages is not a functionTypeError: vis.preloadImages is not a function
web.0 | 2023-03-05 13:18:53.667 | error | can't render tplMfdShutterDialog w00986 on "Home":
web.0 | 2023-03-05 13:18:53.657 | error | 10 - at Function.renderTo (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1449:63)
web.0 | 2023-03-05 13:18:53.653 | error | 9 - at r (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1370:22)
web.0 | 2023-03-05 13:18:53.652 | error | 8 - at Function.frag (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1405:22)
web.0 | 2023-03-05 13:18:53.649 | error | 7 - at Function.hookup (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1418:19)
web.0 | 2023-03-05 13:18:53.645 | error | 6 - at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
web.0 | 2023-03-05 13:18:53.641 | error | 5 - at HTMLDivElement.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1419:98)
web.0 | 2023-03-05 13:18:53.639 | error | 4 - at http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1727:17
web.0 | 2023-03-05 13:18:53.637 | error | 3 - at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
web.0 | 2023-03-05 13:18:53.636 | error | 2 - at Function.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1728:17)
web.0 | 2023-03-05 13:18:53.634 | error | 1 - at Object.eval (tplMfdShutterDialog.js:75:65)
web.0 | 2023-03-05 13:18:53.632 | error | 0 - TypeError: vis.preloadImages is not a functionTypeError: vis.preloadImages is not a function
web.0 | 2023-03-05 13:18:53.631 | error | can't render tplMfdShutterDialog w00984 on "Home":
web.0 | 2023-03-05 13:18:53.464 | error | 10 - at Function.renderTo (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1449:63)
web.0 | 2023-03-05 13:18:53.463 | error | 9 - at r (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1370:22)
web.0 | 2023-03-05 13:18:53.462 | error | 8 - at Function.frag (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1405:22)
web.0 | 2023-03-05 13:18:53.461 | error | 7 - at Function.hookup (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1418:19)
web.0 | 2023-03-05 13:18:53.459 | error | 6 - at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
web.0 | 2023-03-05 13:18:53.458 | error | 5 - at HTMLDivElement.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1419:98)
web.0 | 2023-03-05 13:18:53.456 | error | 4 - at http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1727:17
web.0 | 2023-03-05 13:18:53.452 | error | 3 - at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
web.0 | 2023-03-05 13:18:53.450 | error | 2 - at Function.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1728:17)
web.0 | 2023-03-05 13:18:53.449 | error | 1 - at Object.eval (tplMfdShutterDialog.js:75:65)
web.0 | 2023-03-05 13:18:53.448 | error | 0 - TypeError: vis.preloadImages is not a functionTypeError: vis.preloadImages is not a function
web.0 | 2023-03-05 13:18:53.447 | error | can't render tplMfdShutterDialog w00074 on "Home":
web.0 | 2023-03-05 13:18:53.444 | error | 10 - at Function.renderTo (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1449:63)
web.0 | 2023-03-05 13:18:53.443 | error | 9 - at r (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1370:22)
web.0 | 2023-03-05 13:18:53.442 | error | 8 - at Function.frag (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1405:22)
web.0 | 2023-03-05 13:18:53.441 | error | 7 - at Function.hookup (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1418:19)
web.0 | 2023-03-05 13:18:53.440 | error | 6 - at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
web.0 | 2023-03-05 13:18:53.438 | error | 5 - at HTMLDivElement.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1419:98)
web.0 | 2023-03-05 13:18:53.437 | error | 4 - at http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1727:17
web.0 | 2023-03-05 13:18:53.435 | error | 3 - at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
web.0 | 2023-03-05 13:18:53.434 | error | 2 - at Function.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1728:17)
web.0 | 2023-03-05 13:18:53.433 | error | 1 - at Object.eval (tplMfdShutterDialog.js:75:65)
web.0 | 2023-03-05 13:18:53.431 | error | 0 - TypeError: vis.preloadImages is not a functionTypeError: vis.preloadImages is not a function
web.0 | 2023-03-05 13:18:53.429 | error | can't render tplMfdShutterDialog w00070 on "Home":
web.0 | 2023-03-05 13:18:53.427 | error | 10 - at Function.renderTo (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1449:63)
web.0 | 2023-03-05 13:18:53.425 | error | 9 - at r (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1370:22)
web.0 | 2023-03-05 13:18:53.423 | error | 8 - at Function.frag (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1405:22)
web.0 | 2023-03-05 13:18:53.416 | error | 7 - at Function.hookup (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1418:19)
web.0 | 2023-03-05 13:18:53.414 | error | 6 - at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
web.0 | 2023-03-05 13:18:53.413 | error | 5 - at HTMLDivElement.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1419:98)
web.0 | 2023-03-05 13:18:53.412 | error | 4 - at http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1727:17
web.0 | 2023-03-05 13:18:53.411 | error | 3 - at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
web.0 | 2023-03-05 13:18:53.409 | error | 2 - at Function.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1728:17)
web.0 | 2023-03-05 13:18:53.407 | error | 1 - at Object.eval (tplMfdShutterDialog.js:75:65)
web.0 | 2023-03-05 13:18:53.405 | error | 0 - TypeError: vis.preloadImages is not a functionTypeError: vis.preloadImages is not a function
web.0 | 2023-03-05 13:18:53.404 | error | can't render tplMfdShutterDialog w00069 on "Home":
web.0 | 2023-03-05 13:18:53.375 | error | 10 - at Function.renderTo (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1449:63)
web.0 | 2023-03-05 13:18:53.372 | error | 9 - at r (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1370:22)
web.0 | 2023-03-05 13:18:53.371 | error | 8 - at Function.frag (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1405:22)
web.0 | 2023-03-05 13:18:53.369 | error | 7 - at Function.hookup (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1418:19)
web.0 | 2023-03-05 13:18:53.368 | error | 6 - at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
web.0 | 2023-03-05 13:18:53.366 | error | 5 - at HTMLDivElement.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1419:98)
web.0 | 2023-03-05 13:18:53.365 | error | 4 - at http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1727:17
web.0 | 2023-03-05 13:18:53.363 | error | 3 - at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
web.0 | 2023-03-05 13:18:53.362 | error | 2 - at Function.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1728:17)
web.0 | 2023-03-05 13:18:53.360 | error | 1 - at Object.eval (tplMfdLight.js:70:65)
web.0 | 2023-03-05 13:18:53.358 | error | 0 - TypeError: vis.preloadImages is not a functionTypeError: vis.preloadImages is not a function
web.0 | 2023-03-05 13:18:53.356 | error | can't render tplMfdLight w00058 on "Home":
web.0 | 2023-03-05 13:18:39.303 | info | ==> Connected system.user.admin from ::ffff:10.1.1.129


</body>
</html>`

in der Browserconsole
`Failed to load resource: the server responded with a status of 404 (Not Found)
VM1072:4 Uncaught TypeError: Cannot read properties of undefined (reading 'localization')
    at <anonymous>:4:39
    at Me.<anonymous> (visEngine.jsx:1198:38)
    at Generator.next (<anonymous>)
    at 188.70252e45.chunk.js:29:17406
    at new Promise (<anonymous>)
    at Si (188.70252e45.chunk.js:29:17226)
    at Me.setInnerHTML (visEngine.jsx:1161:42)
    at Me.<anonymous> (visEngine.jsx:1227:29)
    at Generator.next (<anonymous>)
    at r (188.70252e45.chunk.js:29:17264)
adapter/rssfeed/words.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
widgets/fullcalendar/customWidgets.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
visUtils.jsx:892 Error: Cannot load fullcalendar from ./widgets/fullcalendar/customWidgets.js
    at E.onerror (visUtils.jsx:762:43)
(anonymous) @ visUtils.jsx:892
widgets/scheduler/customWidgets.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
visUtils.jsx:892 Error: Cannot load scheduler from ./widgets/scheduler/customWidgets.js
    at E.onerror (visUtils.jsx:762:43)
(anonymous) @ visUtils.jsx:892
visEngine.jsx:1604 Common user CSS not found: Not exists
(anonymous) @ visEngine.jsx:1604
visCanWidget.jsx:1143 can't render tplMfdLight w00058 on "Home": 
renderWidget @ visCanWidget.jsx:1143
visCanWidget.jsx:1147 0 - TypeError: vis.preloadImages is not a functionTypeError: vis.preloadImages is not a function
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 1 -     at Object.eval (tplMfdLight.js:70:65)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 2 -     at Function.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1728:17)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 3 -     at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 4 -     at http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1727:17
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 5 -     at HTMLDivElement.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1419:98)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 6 -     at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 7 -     at Function.hookup (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1418:19)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 8 -     at Function.frag (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1405:22)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 9 -     at r (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1370:22)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 10 -     at Function.renderTo (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1449:63)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1143 can't render tplMfdShutterDialog w00069 on "Home": 
renderWidget @ visCanWidget.jsx:1143
visCanWidget.jsx:1147 0 - TypeError: vis.preloadImages is not a functionTypeError: vis.preloadImages is not a function
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 1 -     at Object.eval (tplMfdShutterDialog.js:75:65)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 2 -     at Function.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1728:17)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 3 -     at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 4 -     at http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1727:17
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 5 -     at HTMLDivElement.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1419:98)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 6 -     at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 7 -     at Function.hookup (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1418:19)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 8 -     at Function.frag (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1405:22)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 9 -     at r (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1370:22)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 10 -     at Function.renderTo (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1449:63)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1143 can't render tplMfdShutterDialog w00070 on "Home": 
renderWidget @ visCanWidget.jsx:1143
visCanWidget.jsx:1147 0 - TypeError: vis.preloadImages is not a functionTypeError: vis.preloadImages is not a function
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 1 -     at Object.eval (tplMfdShutterDialog.js:75:65)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 2 -     at Function.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1728:17)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 3 -     at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 4 -     at http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1727:17
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 5 -     at HTMLDivElement.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1419:98)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 6 -     at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 7 -     at Function.hookup (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1418:19)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 8 -     at Function.frag (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1405:22)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 9 -     at r (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1370:22)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 10 -     at Function.renderTo (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1449:63)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1143 can't render tplMfdShutterDialog w00074 on "Home": 
renderWidget @ visCanWidget.jsx:1143
visCanWidget.jsx:1147 0 - TypeError: vis.preloadImages is not a functionTypeError: vis.preloadImages is not a function
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 1 -     at Object.eval (tplMfdShutterDialog.js:75:65)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 2 -     at Function.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1728:17)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 3 -     at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 4 -     at http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1727:17
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 5 -     at HTMLDivElement.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1419:98)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 6 -     at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 7 -     at Function.hookup (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1418:19)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 8 -     at Function.frag (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1405:22)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 9 -     at r (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1370:22)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 10 -     at Function.renderTo (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1449:63)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1143 can't render tplMfdShutterDialog w00984 on "Home": 
renderWidget @ visCanWidget.jsx:1143
visCanWidget.jsx:1147 0 - TypeError: vis.preloadImages is not a functionTypeError: vis.preloadImages is not a function
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 1 -     at Object.eval (tplMfdShutterDialog.js:75:65)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 2 -     at Function.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1728:17)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 3 -     at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 4 -     at http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1727:17
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 5 -     at HTMLDivElement.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1419:98)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 6 -     at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 7 -     at Function.hookup (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1418:19)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 8 -     at Function.frag (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1405:22)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 9 -     at r (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1370:22)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 10 -     at Function.renderTo (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1449:63)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1143 can't render tplMfdShutterDialog w00986 on "Home": 
renderWidget @ visCanWidget.jsx:1143
visCanWidget.jsx:1147 0 - TypeError: vis.preloadImages is not a functionTypeError: vis.preloadImages is not a function
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 1 -     at Object.eval (tplMfdShutterDialog.js:75:65)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 2 -     at Function.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1728:17)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 3 -     at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 4 -     at http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1727:17
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 5 -     at HTMLDivElement.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1419:98)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 6 -     at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 7 -     at Function.hookup (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1418:19)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 8 -     at Function.frag (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1405:22)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 9 -     at r (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1370:22)
renderWidget @ visCanWidget.jsx:1147
visCanWidget.jsx:1147 10 -     at Function.renderTo (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1449:63)
renderWidget @ visCanWidget.jsx:1147
weatherwidget.html:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing.
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/js/main.edcbd397.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/js/993.caf7ecd4.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/widgets/material-webfont/css/materialdesignicons.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`
