### ISSUE TITLE
Vis2 Fehlendes  DWD-Widgets durch nicht aktiven Adapter bei Installation

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.vis#589]
aktuell v2.0.9
bei der Installation von vis 2.x war der DWD Adapter **nicht** aktiv, somit wurde **kein** widget installiert.
![image](https://user-images.githubusercontent.com/41550245/204528370-2819eb57-bec3-4864-b6ab-32bf50908ab8.png)
das daraus entstehende Problem,
dieses Widget liegt in einer anderen View und ist auf der Startseite als **view in widget** integriert.

öffne ich nun die View **Wetter-front**, wird der Bildschirm schwarz und man kommt nur noch mit dem zurück Button im Browser wieder auf den Vis Editor.
```
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/js/main.1426430e.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/js/398.c8d8d1e7.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/css/697.79098e54.chunk.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/js/26.e8dea23d.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/js/697.7c00624a.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/js/78.756f4070.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
user9.2a94bc8f.svg:1          GET http://10.1.1.10:8082/vis-2-beta/static/media/user9.2a94bc8f.svg 404 (Not Found)
Image (async)
Oo @ main.1426430e.js:1914
co @ main.1426430e.js:1914
jo @ main.1426430e.js:1914
p3 @ main.1426430e.js:1914
D3 @ main.1426430e.js:1914
Zo @ main.1426430e.js:1914
C @ main.1426430e.js:1948
T @ main.1426430e.js:1948
VM3680:4 Uncaught TypeError: Cannot read properties of undefined (reading 'localization')
    at <anonymous>:4:39
    at Xe.<anonymous> (697.7c00624a.chunk.js:29:37779)
    at Generator.next (<anonymous>)
    at 697.7c00624a.chunk.js:29:16218
    at new Promise (<anonymous>)
    at wi (697.7c00624a.chunk.js:29:16038)
    at Xe.setInnerHTML (697.7c00624a.chunk.js:29:37201)
    at Xe.<anonymous> (697.7c00624a.chunk.js:29:38260)
    at Generator.next (<anonymous>)
    at r (697.7c00624a.chunk.js:29:16076)
(anonymous) @ VM3680:4
(anonymous) @ 697.7c00624a.chunk.js:29
(anonymous) @ 697.7c00624a.chunk.js:29
wi @ 697.7c00624a.chunk.js:29
setInnerHTML @ 697.7c00624a.chunk.js:29
(anonymous) @ 697.7c00624a.chunk.js:29
r @ 697.7c00624a.chunk.js:29
Promise.then (async)
l @ 697.7c00624a.chunk.js:29
r @ 697.7c00624a.chunk.js:29
Promise.then (async)
l @ 697.7c00624a.chunk.js:29
(anonymous) @ 697.7c00624a.chunk.js:29
wi @ 697.7c00624a.chunk.js:29
loadWidgets @ 697.7c00624a.chunk.js:29
(anonymous) @ 697.7c00624a.chunk.js:29
Promise.then (async)
Xe @ 697.7c00624a.chunk.js:29
rr @ main.1426430e.js:1912
J4 @ main.1426430e.js:1914
Ao @ main.1426430e.js:1914
kr @ main.1426430e.js:1914
S6 @ main.1426430e.js:1914
yn @ main.1426430e.js:1914
Zo @ main.1426430e.js:1914
C @ main.1426430e.js:1948
T @ main.1426430e.js:1948
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/widgets/material-webfont/css/materialdesignicons.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
info.js:84 Uncaught SyntaxError: Unexpected end of input (at info.js:84:1)
null:1          GET http://10.1.1.10:8082/vis-2-beta/null 404 (Not Found)
main.1426430e.js:1914 TypeError: Cannot read properties of undefined (reading 'split')
    at 697.7c00624a.chunk.js:16:23054
    at Array.map (<anonymous>)
    at Vs (697.7c00624a.chunk.js:16:22907)
    at U6 (main.1426430e.js:1912:20610)
    at Z4 (main.1426430e.js:1914:3237)
    at Ao (main.1426430e.js:1914:46646)
    at kr (main.1426430e.js:1914:41351)
    at S6 (main.1426430e.js:1914:41279)
    at yn (main.1426430e.js:1914:41131)
    at vo (main.1426430e.js:1914:37339)
We @ main.1426430e.js:1914
Ye._.callback @ main.1426430e.js:1914
wa @ main.1426430e.js:1912
Oo @ main.1426430e.js:1914
co @ main.1426430e.js:1914
jo @ main.1426430e.js:1914
p3 @ main.1426430e.js:1914
D3 @ main.1426430e.js:1914
ea @ main.1426430e.js:1914
O3 @ main.1426430e.js:1912
(anonymous) @ main.1426430e.js:1914
main.1426430e.js:1912 Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at 697.7c00624a.chunk.js:16:23054
    at Array.map (<anonymous>)
    at Vs (697.7c00624a.chunk.js:16:22907)
    at U6 (main.1426430e.js:1912:20610)
    at Z4 (main.1426430e.js:1914:3237)
    at Ao (main.1426430e.js:1914:46646)
    at kr (main.1426430e.js:1914:41351)
    at S6 (main.1426430e.js:1914:41279)
    at yn (main.1426430e.js:1914:41131)
    at vo (main.1426430e.js:1914:37339)
(anonymous) @ 697.7c00624a.chunk.js:16
Vs @ 697.7c00624a.chunk.js:16
U6 @ main.1426430e.js:1912
Z4 @ main.1426430e.js:1914
Ao @ main.1426430e.js:1914
kr @ main.1426430e.js:1914
S6 @ main.1426430e.js:1914
yn @ main.1426430e.js:1914
vo @ main.1426430e.js:1914
ea @ main.1426430e.js:1914
O3 @ main.1426430e.js:1912
(anonymous) @ main.1426430e.js:1914
```

**Comment by crunchip77** [comment]
DWD Widgets sind mit v2.0.16 jetzt vorhanden und funktioniert.
