### ISSUE TITLE
unhandled promise rejection: DB closed

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.vis#614]
**Describe the bug**  
During shutdown and boot of iobroker the error in the log was shown

**Screenshots & Logfiles**  
```
vis-2-beta.0
	2022-12-04 11:34:19.253	error	DB closed
vis-2-beta.0
	2022-12-04 11:34:19.251	error	Error: DB closed at Redis.sendCommand (/opt/iobroker/node_modules/ioredis/built/redis/index.js:636:24) at Redis.get (/opt/iobroker/node_modules/ioredis/built/commander.js:122:25) at StateRedisClient.setState (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:657:40) at Adapter.setForeignState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:6194:35)
vis-2-beta.0
	2022-12-04 11:34:18.996	error	unhandled promise rejection: DB closed
vis-2-beta.0
	2022-12-04 11:34:18.990	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
```

**Versions:**  
 - Adapter version: Vis-2-beta v.2.0.10, Admin 6.0.23, js-controller 4.0.23

**Comment by GermanBluefox** [comment]
It is js-controller issue

**Comment by Apollon77** [comment]
No it is not controller. This happens when after unload callback is called any db action is done. So we need to verify that all actions are ended after unload is executed

**Comment by Feuer-sturm** [comment]
During the following updates of the adapters

- vis-2-widgets-gauges from @0.1.9 to @0.1.11
- vis-2-widgets-material from @0.2.9 to @0.2.11

The following "DB closed" errors were shown in the log as well: 

```
2023-03-09 22:09:28.926 - info: host.ioBrokerTestsystem iobroker upgrade vis-2-widgets-gauges@0.1.11 --debug
2023-03-09 22:09:33.231 - info: host.ioBrokerTestsystem iobroker Update vis-2-widgets-gauges from @0.1.9 to @0.1.11
2023-03-09 22:09:36.751 - info: host.ioBrokerTestsystem iobroker NPM version: 9.5.0Installing iobroker.vis-2-widgets-gauges@0.1.11... (System call)
2023-03-09 22:09:54.326 - info: host.ioBrokerTestsystem iobroker
2023-03-09 22:09:54.329 - info: host.ioBrokerTestsystem iobroker changed 1 package in 16s81 packages are looking for funding run `npm fund` for details
2023-03-09 22:09:54.406 - info: host.ioBrokerTestsystem iobroker INFO: Directory "/opt/iobroker/node_modules/iobroker.vis-2-widgets-gauges/www" was not found! Nothing was uploaded or deleted.
2023-03-09 22:09:54.600 - info: host.ioBrokerTestsystem "system.adapter.vis.0" disabled
2023-03-09 22:09:54.744 - info: host.ioBrokerTestsystem "system.adapter.vis.0" enabled
2023-03-09 22:09:54.890 - info: host.ioBrokerTestsystem iobroker Adapter "system.adapter.vis.0" restarted.
2023-03-09 22:09:55.010 - info: host.ioBrokerTestsystem "system.adapter.vis-2-beta.0" disabled
2023-03-09 22:09:55.011 - info: host.ioBrokerTestsystem stopInstance system.adapter.vis-2-beta.0 (force=false, process=true)
2023-03-09 22:09:55.035 - info: vis-2-beta.0 (3724) Got terminate signal TERMINATE_YOURSELF
2023-03-09 22:09:55.051 - info: host.ioBrokerTestsystem "system.adapter.vis-2-beta.0" enabled
2023-03-09 22:09:55.052 - info: host.ioBrokerTestsystem stopInstance system.adapter.vis-2-beta.0 (force=false, process=true)
2023-03-09 22:09:55.072 - info: host.ioBrokerTestsystem iobroker Adapter "system.adapter.vis-2-beta.0" restarted.
2023-03-09 22:09:55.077 - info: host.ioBrokerTestsystem stopInstance system.adapter.vis-2-beta.0 send kill signal
2023-03-09 22:09:55.084 - info: vis-2-beta.0 (3724) Got terminate signal TERMINATE_YOURSELF
2023-03-09 22:09:55.195 - info: host.ioBrokerTestsystem stopInstance system.adapter.vis-2-beta.0 send kill signal
2023-03-09 22:09:55.463 - info: host.ioBrokerTestsystem iobroker Update "system.adapter.vis-2-widgets-gauges.0"
2023-03-09 22:09:55.501 - info: host.ioBrokerTestsystem stopInstance system.adapter.vis-2-widgets-gauges.0 (force=false, process=false)
2023-03-09 22:09:55.544 - info: vis-2-beta.0 (3724) terminating
2023-03-09 22:09:55.547 - info: vis-2-beta.0 (3724) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2023-03-09 22:09:55.577 - info: host.ioBrokerTestsystem iobroker upload [0] vis-2-widgets-gauges.admin /opt/iobroker/node_modules/iobroker.vis-2-widgets-gauges/admin/vis-2-widgets-gauges.png vis-2-widgets-gauges.png image/png
2023-03-09 22:09:56.079 - info: host.ioBrokerTestsystem stopInstance system.adapter.vis-2-beta.0 killing pid 3724
2023-03-09 22:09:56.084 - error: vis-2-beta.0 (3724) Cannot delete file "/widgets/jqui-mfd/img/sani_valve_50.svg": Error: DB closed
2023-03-09 22:09:56.095 - error: vis-2-beta.0 (3724) uncaught exception: Connection is closed.
2023-03-09 22:09:56.098 - error: vis-2-beta.0 (3724) Error: Connection is closed.
at Redis.sendCommand (/opt/iobroker/node_modules/ioredis/built/redis/index.js:636:24)
at Redis.scan (/opt/iobroker/node_modules/ioredis/built/commander.js:122:25)
at ScanStream._read (/opt/iobroker/node_modules/ioredis/built/ScanStream.js:36:41)
at Readable.read (node:internal/streams/readable:496:12)
at resume_ (node:internal/streams/readable:999:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-03-09 22:09:56.101 - error: vis-2-beta.0 (3724) Connection is closed.
2023-03-09 22:09:56.290 - info: host.ioBrokerTestsystem instance system.adapter.vis-2-beta.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2023-03-09 22:09:56.867 - info: host.ioBrokerTestsystem iobroker exit 0
2023-03-09 22:09:58.195 - info: vis.0 (3775) starting. Version 1.4.16 in /opt/iobroker/node_modules/iobroker.vis, node: v18.14.2, js-controller: 4.0.24
2023-03-09 22:09:58.476 - info: host.ioBrokerTestsystem instance system.adapter.vis-2-beta.0 started with pid 3790
2023-03-09 22:09:58.679 - info: vis.0 (3775) vis license is OK.
2023-03-09 22:10:00.933 - info: vis.0 (3775) Terminated (NO_ERROR): Without reason
2023-03-09 22:10:01.918 - info: host.ioBrokerTestsystem instance system.adapter.vis.0 terminated while should be started once
2023-03-09 22:10:03.417 - info: vis-2-beta.0 (3790) starting. Version 2.0.20 in /opt/iobroker/node_modules/iobroker.vis-2-beta, node: v18.14.2, js-controller: 4.0.24
2023-03-09 22:10:03.539 - error: vis-2-beta.0 (3790) No license found for vis. Please get one on https://iobroker.net !
2023-03-09 22:10:03.663 - info: vis-2-beta.0 (3790) config.js changed. Upload.
2023-03-09 22:10:03.817 - info: host.ioBrokerTestsystem iobroker upgrade vis-2-widgets-material@0.2.11 --debug
2023-03-09 22:10:09.021 - info: host.ioBrokerTestsystem iobroker Update vis-2-widgets-material from @0.2.9 to @0.2.11
2023-03-09 22:10:12.196 - info: host.ioBrokerTestsystem iobroker NPM version: 9.5.0
2023-03-09 22:10:12.201 - info: host.ioBrokerTestsystem iobroker Installing iobroker.vis-2-widgets-material@0.2.11... (System call)
2023-03-09 22:10:35.541 - info: host.ioBrokerTestsystem iobroker changed 1 package in 21s81 packages are looking for funding run `npm fund` for detailsINFO: Directory "/opt/iobroker/node_modules/iobroker.vis-2-widgets-material/www" was not found! Nothing was uploaded or deleted.
2023-03-09 22:10:36.002 - info: host.ioBrokerTestsystem "system.adapter.vis.0" disabled
2023-03-09 22:10:36.097 - info: host.ioBrokerTestsystem "system.adapter.vis.0" enabled
2023-03-09 22:10:36.106 - info: host.ioBrokerTestsystem iobroker Adapter "system.adapter.vis.0" restarted.
2023-03-09 22:10:36.423 - info: host.ioBrokerTestsystem "system.adapter.vis-2-beta.0" disabled
2023-03-09 22:10:36.426 - info: host.ioBrokerTestsystem stopInstance system.adapter.vis-2-beta.0 (force=false, process=true)
2023-03-09 22:10:36.490 - info: vis-2-beta.0 (3790) Got terminate signal TERMINATE_YOURSELF
2023-03-09 22:10:36.562 - info: host.ioBrokerTestsystem "system.adapter.vis-2-beta.0" enabled
2023-03-09 22:10:36.563 - info: host.ioBrokerTestsystem stopInstance system.adapter.vis-2-beta.0 (force=false, process=true)
2023-03-09 22:10:36.607 - info: host.ioBrokerTestsystem stopInstance system.adapter.vis-2-beta.0 send kill signal
2023-03-09 22:10:36.617 - info: host.ioBrokerTestsystem iobroker Adapter "system.adapter.vis-2-beta.0" restarted.
2023-03-09 22:10:36.633 - info: vis-2-beta.0 (3790) Got terminate signal TERMINATE_YOURSELF
2023-03-09 22:10:36.806 - info: host.ioBrokerTestsystem stopInstance system.adapter.vis-2-beta.0 send kill signal
2023-03-09 22:10:37.047 - info: vis-2-beta.0 (3790) terminating
2023-03-09 22:10:37.051 - info: vis-2-beta.0 (3790) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2023-03-09 22:10:37.142 - info: host.ioBrokerTestsystem iobroker Update "system.adapter.vis-2-widgets-material.0"
2023-03-09 22:10:37.190 - info: host.ioBrokerTestsystem stopInstance system.adapter.vis-2-widgets-material.0 (force=false, process=false)
2023-03-09 22:10:37.428 - info: host.ioBrokerTestsystem iobroker upload [0] vis-2-widgets-material.admin /opt/iobroker/node_modules/iobroker.vis-2-widgets-material/admin/vis-2-widgets-material.png vis-2-widgets-material.png image/png
2023-03-09 22:10:37.612 - info: host.ioBrokerTestsystem stopInstance system.adapter.vis-2-beta.0 killing pid 3790
2023-03-09 22:10:37.677 - error: vis-2-beta.0 (3790) Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/static/media/Bedroom.2a16d8d98fafe965fd1b.svg: DB closed
2023-03-09 22:10:37.690 - error: vis-2-beta.0 (3790) Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/static/media/Boiler Room.548e785e2f92b45f72b3.svg: DB closed
2023-03-09 22:10:37.717 - error: vis-2-beta.0 (3790) Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/static/media/Carport.8337662544b9e95f4b27.svg: DB closed
2023-03-09 22:10:37.728 - error: vis-2-beta.0 (3790) Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/static/media/Ceiling Spotlights.485822441b5df3b3384a.svg: DB closed
2023-03-09 22:10:37.733 - error: vis-2-beta.0 (3790) Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/static/media/Cellar.7ec1b1803a2437c8b78c.svg: DB closed
2023-03-09 22:10:37.745 - error: vis-2-beta.0 (3790) Error: Cannot upload /opt/iobroker/node_modules/iobroker.vis-2-beta/www/static/media/Chamber.71daaa4d14262dae029b.svg: DB closed
2023-03-09 22:10:38.101 - info: host.ioBrokerTestsystem instance system.adapter.vis-2-beta.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2023-03-09 22:10:38.826 - info: host.ioBrokerTestsystem iobroker exit 0
2023-03-09 22:10:40.074 - info: host.ioBrokerTestsystem instance system.adapter.vis-2-beta.0 started with pid 3850
2023-03-09 22:10:40.357 - info: vis.0 (3839) starting. Version 1.4.16 in /opt/iobroker/node_modules/iobroker.vis, node: v18.14.2, js-controller: 4.0.24
2023-03-09 22:10:40.747 - info: vis.0 (3839) vis license is OK.
2023-03-09 22:10:42.752 - info: vis.0 (3839) Terminated (NO_ERROR): Without reason
2023-03-09 22:10:43.540 - info: host.ioBrokerTestsystem instance system.adapter.vis.0 terminated while should be started once
2023-03-09 22:10:43.821 - info: vis-2-beta.0 (3850) starting. Version 2.0.20 in /opt/iobroker/node_modules/iobroker.vis-2-beta, node: v18.14.2, js-controller: 4.0.24
```

**Comment by GermanBluefox** [comment]
So, If I change some vis widgets file, or vis itself and restart the vis, the procedure is rather long and can last for up to minute. If during this vis-restart I will stop the js-controller, I guess we will get all these errors.

**Comment by Feuer-sturm** [comment]
issue seems to be fixed
vis 2.0.28
js-controller 5.0.1-alpha.0-20230418-efa3e809
