### ISSUE TITLE
Editor turns black after selecting an option under "Show in Views"

### ISSUE THREAD

**Issue by Phyxx001** [ioBroker/ioBroker.vis#693]
**Describe the bug**  
When on option under General/ Show in Views the editor turns black. F5 will bring you back, but no option under "Show in Views" will be selected

**To Reproduce**  
1. Go to any object with the option "Show in Views"
2. Click on Show in Views.
3. Select any option there.
4. See error: Editor turns black

**Expected behavior**  
The option will be selected and other options could be selected with further clicks.

**Screenshots & Logfiles**  
`DevTools failed to load source map: Could not load content for http://192.168.178.113:8082/lib/js/socket.io.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.113:8082/vis-2-beta/static/js/main.7b76ba87.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
bootstrap.jsx:20 iobroker.vis-2-beta@2.0.24 using theme "dark"
main.7b76ba87.js:658 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

main.7b76ba87.js:658 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
main.7b76ba87.js:658 Help us to create open source project with reactJS!
main.7b76ba87.js:658 See you :)
DevTools failed to load source map: Could not load content for http://192.168.178.113:8082/vis-2-beta/static/js/236.3eae57b4.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
VM2516:86 Version lcars: 1.0.4
main.7b76ba87.js:658 Translate: show code
main.7b76ba87.js:658 Translate: ==
main.7b76ba87.js:658 Translate: !=
main.7b76ba87.js:658 Translate: <=
main.7b76ba87.js:658 Translate: >=
main.7b76ba87.js:658 Translate: <
main.7b76ba87.js:658 Translate: >
main.7b76ba87.js:658 Translate: consist
main.7b76ba87.js:658 Translate: not consist
main.7b76ba87.js:658 Translate: exist
main.7b76ba87.js:658 Translate: not exist
main.7b76ba87.js:658 Translate: disabled
visEngine.jsx:1594 [2023-04-05T09:58:36.511Z] +SUBSCRIBE: openknx.0.Beleuchtung.Rückmeldung_schalten_(ein_aus_1Bit)_-_kopieren.E5_Büro_Licht_Deckenlampe_Rückmeldung_Schalten
visEngine.jsx:1594 [2023-04-05T09:58:36.512Z] +SUBSCRIBE: openknx.0.Beleuchtung.Schalten__ein_aus_1Bit)_-_Neuanlage_immer_hier.E5_Büro_Licht_Deckenlampe_Schalten
main.7b76ba87.js:1914 TypeError: v.join is not a function
    at renderValue (WidgetField.jsx:781:75)
    at main.7b76ba87.js:812:82358
    at An (main.7b76ba87.js:1912:20592)
    at fa (main.7b76ba87.js:1914:1607)
    at _c (main.7b76ba87.js:1914:47518)
    at Uo (main.7b76ba87.js:1914:41085)
    at Fc (main.7b76ba87.js:1914:41013)
    at Ha (main.7b76ba87.js:1914:40865)
    at _o (main.7b76ba87.js:1914:37106)
    at vo (main.7b76ba87.js:1914:36034)
R5 @ main.7b76ba87.js:1914
_.callback @ main.7b76ba87.js:1914
Ua @ main.7b76ba87.js:1912
jt @ main.7b76ba87.js:1914
Ue @ main.7b76ba87.js:1914
Je @ main.7b76ba87.js:1914
yc @ main.7b76ba87.js:1914
Fr @ main.7b76ba87.js:1914
vo @ main.7b76ba87.js:1914
x @ main.7b76ba87.js:1948
w @ main.7b76ba87.js:1948
main.7b76ba87.js:1914 Uncaught TypeError: v.join is not a function
    at renderValue (WidgetField.jsx:781:75)
    at main.7b76ba87.js:812:82358
    at An (main.7b76ba87.js:1912:20592)
    at fa (main.7b76ba87.js:1914:1607)
    at _c (main.7b76ba87.js:1914:47518)
    at Uo (main.7b76ba87.js:1914:41085)
    at Fc (main.7b76ba87.js:1914:41013)
    at Ha (main.7b76ba87.js:1914:40865)
    at _o (main.7b76ba87.js:1914:37106)
    at vo (main.7b76ba87.js:1914:36034)`

The following messages are displayed directly after clicking any option under "Show in Views"
![image](https://user-images.githubusercontent.com/129990481/230173623-ce0f4d05-f7d2-4f95-ae6c-5d5f7c25ddee.png)

**Versions:**  
 - Adapter version: vis-2-beta v2.0.24
 - JS-Controller version: <js-controller-version> 4.0.24
 - Node version: <node-version> v16.19.1
 - Operating system: <os-name> LXC Container under Proxmox with template "debian-11-standard 11.6-1 amd64"

**Additional context**  
Browser running under Windows 11. Same issue under Edge and Vivaldi.

**Comment by Phyxx001** [comment]
Hi, perfect work. I can confirm that, after the upgrade, it is working nice and smooth.
Thanks a lot!
Bjoern
