### ISSUE TITLE
VIS2 2.1.4 - Material Widgets - Buttons funktionieren nicht

### ISSUE THREAD

**Issue by Volker88** [ioBroker/ioBroker.vis#747]
Nach dem update von VIS 2.0.36 auf 2.1.4 funktionieren die buttons erstellt mit Material Widgets nicht mehr.
Material Widgets version ist 0.3.1

Google Chrome bringt die folgende Meldung in der Konsole:
Ich habe in der VIS nur 1 Widget mit 2 buttons. Daher verstehe ich auch nicht die ganzen Fehler bezüglich "gauges" und "energy"

bootstrap.jsx:20 iobroker.vis-2-beta@2.1.4 using theme "colored"
main.ff8ee3ca.js:2 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

main.ff8ee3ca.js:2 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
main.ff8ee3ca.js:2 Help us to create open source project with reactJS!
main.ff8ee3ca.js:2 See you :)
instrument.ts:132 Metro version: "1.2.0"
instrument.ts:132 Version Info-Adapter-Widget: 0.0.9
instrument.ts:132 common.visWidgets.i18n is deprecated. Use common.visWidgets.vis2materialWidgets.i18n instead.
(anonymous) @ instrument.ts:132
instrument.ts:132 common.visWidgets.i18n is deprecated. Use common.visWidgets.vis2energyWidgets.i18n instead.
(anonymous) @ instrument.ts:132
instrument.ts:132 common.visWidgets.i18n is deprecated. Use common.visWidgets.vis2gaugeWidgets.i18n instead.
(anonymous) @ instrument.ts:132
instrument.ts:132 Common user CSS not found: Not exists
(anonymous) @ instrument.ts:132
src_Switches_jsx.7b6374cd.chunk.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getObject')
    at k.<anonymous> (src_Switches_jsx.7b6374cd.chunk.js:1:7721)
    at Generator.next (<anonymous>)
    at src_Switches_jsx.7b6374cd.chunk.js:1:2582
    at new Promise (<anonymous>)
    at S (src_Switches_jsx.7b6374cd.chunk.js:1:2402)
    at k.propertiesUpdate (src_Switches_jsx.7b6374cd.chunk.js:1:7582)
    at k.<anonymous> (src_Switches_jsx.7b6374cd.chunk.js:1:9424)
    at Generator.next (<anonymous>)
    at src_Switches_jsx.7b6374cd.chunk.js:1:2582
    at new Promise (<anonymous>)
    at S (src_Switches_jsx.7b6374cd.chunk.js:1:2402)
    at k.componentDidMount (src_Switches_jsx.7b6374cd.chunk.js:1:9338)
    at gl (main.ff8ee3ca.js:2:6335173)
    at Vl (main.ff8ee3ca.js:2:6334946)
    at Hl (main.ff8ee3ca.js:2:6334482)
    at main.ff8ee3ca.js:2:6346319
    at xs (main.ff8ee3ca.js:2:6346834)
    at as (main.ff8ee3ca.js:2:6339292)
    at x (main.ff8ee3ca.js:2:7769655)
    at MessagePort.Z (main.ff8ee3ca.js:2:7770189)
src_Switches_jsx.7b6374cd.chunk.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getObject')
    at k.<anonymous> (src_Switches_jsx.7b6374cd.chunk.js:1:7721)
    at Generator.next (<anonymous>)
    at src_Switches_jsx.7b6374cd.chunk.js:1:2582
    at new Promise (<anonymous>)
    at S (src_Switches_jsx.7b6374cd.chunk.js:1:2402)
    at k.propertiesUpdate (src_Switches_jsx.7b6374cd.chunk.js:1:7582)
    at k.<anonymous> (src_Switches_jsx.7b6374cd.chunk.js:1:28523)
    at Generator.next (<anonymous>)
    at src_Switches_jsx.7b6374cd.chunk.js:1:2582
    at new Promise (<anonymous>)
    at S (src_Switches_jsx.7b6374cd.chunk.js:1:2402)
    at src_Switches_jsx.7b6374cd.chunk.js:1:28464
    at a (helpers.ts:98:1)
src_Switches_jsx.7b6374cd.chunk.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getObject')
    at k.<anonymous> (src_Switches_jsx.7b6374cd.chunk.js:1:7721)
    at Generator.next (<anonymous>)
    at src_Switches_jsx.7b6374cd.chunk.js:1:2582
    at new Promise (<anonymous>)
    at S (src_Switches_jsx.7b6374cd.chunk.js:1:2402)
    at k.propertiesUpdate (src_Switches_jsx.7b6374cd.chunk.js:1:7582)
    at k.<anonymous> (src_Switches_jsx.7b6374cd.chunk.js:1:28523)
    at Generator.next (<anonymous>)
    at src_Switches_jsx.7b6374cd.chunk.js:1:2582
    at new Promise (<anonymous>)
    at S (src_Switches_jsx.7b6374cd.chunk.js:1:2402)
    at src_Switches_jsx.7b6374cd.chunk.js:1:28464
    at a (helpers.ts:98:1)
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/lib/js/socket.io.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/static/js/main.ff8ee3ca.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-energy/static/js/src_i18n_de_json-src_i18n_en_json-src_i18n_es_json-src_i18n_fr_json-src_i18n_it_json-src_i18n-67bb96.0e530749.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-energy/static/js/src_translations_js.dab10b42.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_translations_js.4825f038.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-gauges/static/js/src_translations_js.9bdd0318.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_i18n_de_json-src_i18n_en_json-src_i18n_es_json-src_i18n_fr_json-src_i18n_it_json-src_i18n-67bb96.f0d03154.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-gauges/static/js/src_i18n_de_json-src_i18n_en_json-src_i18n_es_json-src_i18n_fr_json-src_i18n_it_json-src_i18n-67bb96.d19fe4f4.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-energy/static/js/src_ConsumptionComparison_jsx.0f071e3f.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-energy/static/js/src_Consumption_jsx.79ef8c21.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-energy/static/js/src_IntervalSelector_jsx.4e7481ae.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-energy/static/js/src_Distribution_jsx.6b5ce11d.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Generic_jsx-src_ObjectChart_jsx.4419e927.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Thermostat_jsx.00661837.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Static_jsx.de18c1d2.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
src_Switches_jsx.7b6374cd.chunk.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getObject')
    at k.<anonymous> (src_Switches_jsx.7b6374cd.chunk.js:1:7721)
    at Generator.next (<anonymous>)
    at src_Switches_jsx.7b6374cd.chunk.js:1:2582
    at new Promise (<anonymous>)
    at S (src_Switches_jsx.7b6374cd.chunk.js:1:2402)
    at k.propertiesUpdate (src_Switches_jsx.7b6374cd.chunk.js:1:7582)
    at k.<anonymous> (src_Switches_jsx.7b6374cd.chunk.js:1:28523)
    at Generator.next (<anonymous>)
    at src_Switches_jsx.7b6374cd.chunk.js:1:2582
    at new Promise (<anonymous>)
    at S (src_Switches_jsx.7b6374cd.chunk.js:1:2402)
    at src_Switches_jsx.7b6374cd.chunk.js:1:28464
    at a (helpers.ts:98:1)
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
S @ src_Switches_jsx.7b6374cd.chunk.js:1
propertiesUpdate @ src_Switches_jsx.7b6374cd.chunk.js:1
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
S @ src_Switches_jsx.7b6374cd.chunk.js:1
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
a @ helpers.ts:98
Promise.then (async)
n @ src_Switches_jsx.7b6374cd.chunk.js:1
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
S @ src_Switches_jsx.7b6374cd.chunk.js:1
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
a @ helpers.ts:98
setTimeout (async)
(anonymous) @ trycatch.ts:119
renderWidgetBody @ src_Switches_jsx.7b6374cd.chunk.js:1
value @ visBaseWidget.jsx:1583
value @ visRxWidget.jsx:586
bi @ main.ff8ee3ca.js:2
wi @ main.ff8ee3ca.js:2
yl @ main.ff8ee3ca.js:2
Vs @ main.ff8ee3ca.js:2
Ms @ main.ff8ee3ca.js:2
zs @ main.ff8ee3ca.js:2
as @ main.ff8ee3ca.js:2
x @ main.ff8ee3ca.js:2
Z @ main.ff8ee3ca.js:2
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Actual_jsx.29743391.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Switches_jsx.7b6374cd.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Clock_jsx.d2716ce1.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Blinds_jsx.8e8de914.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_ViewInWidget_jsx.03f08ba1.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_SimpleState_jsx.130559fc.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Camera_jsx.725fc75d.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Security_jsx.00b3f001.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Player_jsx.40505f98.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-material/static/js/src_Html_jsx.704e0bc4.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-gauges/static/js/src_ColorGauge_jsx.63c3ad5c.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-gauges/static/js/src_WaterGauge_jsx.6107aae7.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-gauges/static/js/src_BatteryGauge_jsx.cf07ea6e.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.20.52:8082/vis-2-beta/widgets/vis-2-widgets-material/static/css/src_Map_jsx-node_modules_leaflet_dist_leaflet_css.7e85f6b9.chunk.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
src_Switches_jsx.7b6374cd.chunk.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getObject')
    at k.<anonymous> (src_Switches_jsx.7b6374cd.chunk.js:1:7721)
    at Generator.next (<anonymous>)
    at src_Switches_jsx.7b6374cd.chunk.js:1:2582
    at new Promise (<anonymous>)
    at S (src_Switches_jsx.7b6374cd.chunk.js:1:2402)
    at k.propertiesUpdate (src_Switches_jsx.7b6374cd.chunk.js:1:7582)
    at k.<anonymous> (src_Switches_jsx.7b6374cd.chunk.js:1:28523)
    at Generator.next (<anonymous>)
    at src_Switches_jsx.7b6374cd.chunk.js:1:2582
    at new Promise (<anonymous>)
    at S (src_Switches_jsx.7b6374cd.chunk.js:1:2402)
    at src_Switches_jsx.7b6374cd.chunk.js:1:28464
    at a (helpers.ts:98:1)
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
S @ src_Switches_jsx.7b6374cd.chunk.js:1
propertiesUpdate @ src_Switches_jsx.7b6374cd.chunk.js:1
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
S @ src_Switches_jsx.7b6374cd.chunk.js:1
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
a @ helpers.ts:98
Promise.then (async)
n @ src_Switches_jsx.7b6374cd.chunk.js:1
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
S @ src_Switches_jsx.7b6374cd.chunk.js:1
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
a @ helpers.ts:98
setTimeout (async)
(anonymous) @ trycatch.ts:119
renderWidgetBody @ src_Switches_jsx.7b6374cd.chunk.js:1
value @ visBaseWidget.jsx:1583
value @ visRxWidget.jsx:586
bi @ main.ff8ee3ca.js:2
wi @ main.ff8ee3ca.js:2
yl @ main.ff8ee3ca.js:2
Vs @ main.ff8ee3ca.js:2
Ms @ main.ff8ee3ca.js:2
zs @ main.ff8ee3ca.js:2
as @ main.ff8ee3ca.js:2
x @ main.ff8ee3ca.js:2
Z @ main.ff8ee3ca.js:2
src_Switches_jsx.7b6374cd.chunk.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getObject')
    at k.<anonymous> (src_Switches_jsx.7b6374cd.chunk.js:1:7721)
    at Generator.next (<anonymous>)
    at src_Switches_jsx.7b6374cd.chunk.js:1:2582
    at new Promise (<anonymous>)
    at S (src_Switches_jsx.7b6374cd.chunk.js:1:2402)
    at k.propertiesUpdate (src_Switches_jsx.7b6374cd.chunk.js:1:7582)
    at k.<anonymous> (src_Switches_jsx.7b6374cd.chunk.js:1:28523)
    at Generator.next (<anonymous>)
    at src_Switches_jsx.7b6374cd.chunk.js:1:2582
    at new Promise (<anonymous>)
    at S (src_Switches_jsx.7b6374cd.chunk.js:1:2402)
    at src_Switches_jsx.7b6374cd.chunk.js:1:28464
    at a (helpers.ts:98:1)
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
S @ src_Switches_jsx.7b6374cd.chunk.js:1
propertiesUpdate @ src_Switches_jsx.7b6374cd.chunk.js:1
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
S @ src_Switches_jsx.7b6374cd.chunk.js:1
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
a @ helpers.ts:98
Promise.then (async)
n @ src_Switches_jsx.7b6374cd.chunk.js:1
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
S @ src_Switches_jsx.7b6374cd.chunk.js:1
(anonymous) @ src_Switches_jsx.7b6374cd.chunk.js:1
a @ helpers.ts:98
setTimeout (async)
(anonymous) @ trycatch.ts:119
renderWidgetBody @ src_Switches_jsx.7b6374cd.chunk.js:1
value @ visBaseWidget.jsx:1583
value @ visRxWidget.jsx:586
bi @ main.ff8ee3ca.js:2
wi @ main.ff8ee3ca.js:2
yl @ main.ff8ee3ca.js:2
Vs @ main.ff8ee3ca.js:2
Ms @ main.ff8ee3ca.js:2
zs @ main.ff8ee3ca.js:2
as @ main.ff8ee3ca.js:2
x @ main.ff8ee3ca.js:2
Z @ main.ff8ee3ca.js:2
`

**Comment by Volker88** [comment]
Nachdem ich Material Widgets heute auf v0.8.3 und vis2 auf 2.1.5 aktualisiert habe tritt der Fehler nicht mehr auf
