### ISSUE TITLE
Vis übernimmt states nicht korrekt

### ISSUE THREAD

**Issue by E-Stegemann** [ioBroker/ioBroker.vis#779]
**Describe the bug**  
Hallo Zusammen, ich habe das Problem, dass mein Vis Projekt die Zustände vieler Objekte nicht korrekt wiedergibt. Zum Beispiel habe ich eine View um das Licht im Wohnzimmer zu steuern. Das gesamte Zimmer oder jede einzelne Leuchte. Schalte ich jetzt das gesamte Wohnzimmer an, bleiben die States der einzelnen Leuchten auf "aus", obwohl ich in den Objekten sehen kann, dass deren State auf "An" (true) ist. Erst wenn ich den Screen aktualisiere, wird der korrekte Zustand in der vis gezeigt. Es macht mich wahnsinnig, da ich den Fehler nicht finden kann und sehr lange an meiner Vis gearbeitet habe.
Screenshots habe ich beigefügt, die zeigen am Beispiel "Wohnzimmer gesamt An", dass bspw. die Leuchte "Tisch oben" in der Vis als "Aus" angeizeigt wird, in den Objekten jedoch der Wert auf "An" (true) steht.

**Expected behavior**  
Ich würde erwarten, wenn ich das gesamte Wohnzimmer anschalte, dass bspw die States der einzelnen Leuchten, den korrekten Wert anzeigen --> true / An

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
![Bsp Tisch oben in objekte](https://github.com/ioBroker/ioBroker.vis/assets/71043988/fc1b2a21-cb83-455f-a126-3ae992966317)
![States werden nicht übernommen](https://github.com/ioBroker/ioBroker.vis/assets/71043988/1b603f27-2bc0-41ea-a3fd-0364197186f5)

**Versions:**  
 - Adapter version: v1.4.14
 - JS-Controller version: 5.0.12
 - Node version: v18.16.0
 - Operating system: Debian

EDIT: Über die Chrome Fehlerkonsole konnte ich folgende Fehlermeldung auslesen:
`Error: Error: can't create states object for hue.0.Wohnzimmer.anyOn(TypeError: Cannot read properties of undefined (reading 'style')): "TypeError: Cannot read properties of undefined (reading 'style')\n    at http://192.168.178.252:8082/vis/widgets/vis-inventwo/js/vis-inventwo.js:6005:17\n    at Array.forEach (<anonymous>)\n    at updateWidget (http://192.168.178.252:8082/vis/widgets/vis-inventwo/js/vis-inventwo.js:6003:13)\n    at a.<anonymous> (http://192.168.178.252:8082/vis/widgets/vis-inventwo/js/vis-inventwo.js:5932:5)\n    at t.dispatch (http://192.168.178.252:8082/vis/lib/js/can.custom.min.js:18:1252)\n    at Object.stop (http://192.168.178.252:8082/vis/lib/js/can.custom.min.js:44:451)\n    at a._setAttrs (http://192.168.178.252:8082/vis/lib/js/can.custom.min.js:48:4021)\n    at a.attr (http://192.168.178.252:8082/vis/lib/js/can.custom.min.js:48:1571)\n    at Object.updateState (http://192.168.178.252:8082/vis/js/vis.js:3042:33)\n    at http://192.168.178.252:8082/vis/js/vis.js:3730:21"`
Leider kann ich mit dieser nur geringfügig was anfangen.
Ich hoffe jemand kann mir an dieser Stelle behilflich sein.
Danke und Gruß,
Eric

**Comment by Feuer-sturm** [comment]
@E-Stegemann Hat es einen Grund, warum du beim vis Adapter die Adapter version: v1.4.14 installiert hast und nicht die stable 1.4.16?
Was für ein Widget verwendest du denn in deiner VIS, um den runden Status für "Tisch oben" anzuzeigen?

**Comment by E-Stegemann** [comment]
@Feuer-sturm den vis Adapter habe ich noch nicht aktualisiert. Alle Schalter sind inventwo widgets. Mittlerweile habe ich herausgefunden, was den Fehler verursacht. Der Hue Adapter liefert neben den Leuchten selbst, auch die Raumgruppen. Für das Wohnzimmer Gesamt habe ich das Schalter Widget auf den "On" State des Raumes Wohnzimmer verknüpft. Scheinbar kommt vis nicht mit den Hue Räumen zurecht, da sobald ich den Schalter "Wohnzimmer gesamt" beträgt habe, ging in meiner Visualisierung nichts mehr. Lösche ich den besagten Schalter (der auf den State im Raum Wohnzimmer geht), läuft alles wie es soll. 

Ich habe mir jetzt erstmal eine Alternative via Blockly gebaut, um das gesamte Wohnzimmer zu schalten. Dennoch verstehe ich nicht, warum sich die Vis beim Schalten des Raum States aufhängt.

**Comment by Feuer-sturm** [comment]
@E-Stegemann vielleicht hängt das Verhalten was du beobachtest mit dieser Diskussion zusammen https://forum.iobroker.net/topic/67996/neue-stable-versionen-der-adapter-web-socketio-und-ws/99?_=1696333046071

Am besten einiges nach oben scrollen in dem Beitrag, um den Zusammenhang besser zu verstehen.

**Comment by bahnuhr** [comment]
Das Problem ist bei mir auch wieder da.
Die Anzeige in vis 1 aktualisiert nicht.
web 6.2.3
ws 2.5.11

**Comment by GermanBluefox** [comment]
> Das Problem ist bei mir auch wieder da. Die Anzeige in vis 1 aktualisiert nicht. web 6.2.3 ws 2.5.11

Was hat das mit dem oben geschriebenen Problem zu tun? Da ist die Fehlermeldung über inventwo: `"TypeError: Cannot read properties of undefined (reading 'style')\n    at http://192.168.178.252:8082/vis/widgets/vis-inventwo/js/vis-inventwo.js:6005:`
Dadurch dass es der Fehler aufgetreten ist, werden keine weitere Scripts ausgeführt.
