### ISSUE TITLE
can't render tplMetroTileNav

### ISSUE THREAD

**Issue by BassT23** [ioBroker/ioBroker.vis#864]
Hi @ll,

seit dem letzten update von vis-2 (v2.9.64)

habe ich haufenweise fehlermeldungen:

```
web.1 | 2024-10-24 19:23:32.381 | error | 10 - at Function.renderTo (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1449:63)
web.1 | 2024-10-24 19:23:32.376 | error | 9 - at r (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1370:22)
web.1 | 2024-10-24 19:23:32.376 | error | 8 - at Function.frag (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1405:22)
web.1 | 2024-10-24 19:23:32.375 | error | 7 - at Function.hookup (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1418:19)
web.1 | 2024-10-24 19:23:32.375 | error | 6 - at a.each (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:343:211)
web.1 | 2024-10-24 19:23:32.375 | error | 5 - at HTMLDivElement.<anonymous> (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1419:98)
web.1 | 2024-10-24 19:23:32.375 | error | 4 - at http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1727:17
web.1 | 2024-10-24 19:23:32.372 | error | 3 - at a.each (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:343:211)
web.1 | 2024-10-24 19:23:32.372 | error | 2 - at Function.<anonymous> (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1728:17)
web.1 | 2024-10-24 19:23:32.372 | error | 1 - at Object.eval (tplMetroTileNav.js:21:77)
web.1 | 2024-10-24 19:23:32.370 | error | 0 - TypeError: vis.binds.basic.navigation is not a functionTypeError: vis.binds.basic.navigation is not a function
web.1 | 2024-10-24 19:23:32.368 | error | can't render tplMetroTileNav w000032 on "101_Navi":
```

Metro Tile Nav buttens laufen nicht mehr, ...
reinstall von metro widget hilft nicht :(

_Originally posted by @BassT23 in https://github.com/ioBroker/ioBroker.vis-2/issues/37#issuecomment-2435911142_

**Comment by mcm1957** [comment]
@BassT23
**Are you sure that this issue is correct here?**

This repository contains iobroker.vis. But you ssem to have a problem with iobroker,vis-2. I do not see any relation to iobroker.vis.

And as always - please add VERSION Information:

adapter (version and which vis?)
adapter (shich material adapter and version)
js-controller
admin
node

**Comment by BassT23** [comment]
moded to:
https://github.com/ioBroker/ioBroker.vis-2/issues/483
